# -*- coding: utf-8 -*-
"""
Embedded Course Simulations — Pre-solved, verified course examples
for Visual Math Lab.

Source: Math Course AI PDFs + manually verified constructs.
These are loaded at startup so the user sees ready-made simulations
before any dynamic scanning.
"""

from pathlib import Path

from app_paths import resources_dir as _resources_dir

RESOURCES_DIR = _resources_dir()

EMBEDDED_COURSE_SIMULATIONS = [
    # =================================================================
    # A. Slope-Intercept (3)
    # =================================================================
    {
        "id": "emb_alg1_slope_intercept_001",
        "source_type": "embedded",
        "title": "Algebra 1 — Slope-intercept: m = 1/2, point = (0, -2)",
        "course": "Algebra (course notes)",
        "section": "Functions and graphing — Slope",
        "source_pdf": "Algebra/01 Algebra 1/02 Notes/Notes by section/05 Functions and graphing/02 Slope.pdf",
        "page_number": 1,
        "question_text": "Find the slope-intercept form of the line that passes through (0, -2) and has a slope of 1/2.",
        "normalized_question": "Find the slope-intercept form of the line that passes through (0, -2) and has a slope of 1/2.",
        "problem_type": "slope_intercept",
        "parameters": {"m": 0.5, "b": -2.0, "point": [0.0, -2.0]},
        "answer": "y = 1/2x - 2",
        "alternate_answer": None,
        "solution_text": "A. Given: m = 1/2, point = (0, -2)\nB. Need: slope-intercept form y = mx + b\nC. Formula: y = mx + b\nD. Substitute: -2 = (1/2)(0) + b\nE. Solve: b = -2\nF. Final: y = 1/2x - 2",
        "real_life_text": "Imagine a ramp or a straight road. The starting height is -2 (y-intercept). For every 2 units you move to the right (run), you go up 1 unit (rise). That rise-over-run ratio is the slope 1/2, which tells you how steep the ramp is.",
        "real_life_text_tr": "Bunu bir rampa veya duz bir yol gibi dusun. Baslangic yuksekligi -2 (y-kesme noktasi). Saga dogru her 2 birim gittiginde (yatay), 1 birim yukari cikarsin (dikey). Bu dikey/yatay orani egimdir (1/2); rampanin ne kadar dik oldugunu gosterir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "emb_alg1_slope_intercept_002",
        "source_type": "embedded",
        "title": "Algebra 1 — Slope-intercept: m = -3, point = (0, 5)",
        "course": "Algebra (course notes)",
        "section": "Functions and graphing — Slope",
        "source_pdf": "Algebra/01 Algebra 1/02 Notes/Notes by section/05 Functions and graphing/02 Slope.pdf",
        "page_number": 2,
        "question_text": "A line has slope -3 and passes through (0, 5). Write the equation in slope-intercept form.",
        "normalized_question": "A line has slope -3 and passes through (0, 5). Write the equation in slope-intercept form.",
        "problem_type": "slope_intercept",
        "parameters": {"m": -3.0, "b": 5.0, "point": [0.0, 5.0]},
        "answer": "y = -3x + 5",
        "alternate_answer": None,
        "solution_text": "A. Given: m = -3, point = (0, 5)\nB. Need: slope-intercept form y = mx + b\nC. Formula: y = mx + b\nD. Substitute: 5 = -3(0) + b\nE. Solve: b = 5\nF. Final: y = -3x + 5",
        "real_life_text": "Think of a slide going down from a platform 5 meters high. For every 1 meter you walk forward, you drop 3 meters. The slope -3 tells you the slide is steep and descending.",
        "real_life_text_tr": "5 metre yuksekliginde bir platformdan inen bir kaydirak dusun. Her 1 metre ileri gittiginde 3 metre asagi inersin. Egim -3, kaydiragin dik ve asagi dogru oldugunu soyler.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "emb_alg1_slope_intercept_003",
        "source_type": "embedded",
        "title": "Algebra 1 — Slope-intercept: m = 2/3, point = (0, 1)",
        "course": "Algebra (course notes)",
        "section": "Functions and graphing — Slope",
        "source_pdf": "Algebra/01 Algebra 1/02 Notes/Notes by section/05 Functions and graphing/03 Point-slope and slope-intercept forms of a line.pdf",
        "page_number": 1,
        "question_text": "Write the slope-intercept equation of a line with slope 2/3 that passes through (0, 1).",
        "normalized_question": "Write the slope-intercept equation of a line with slope 2/3 that passes through (0, 1).",
        "problem_type": "slope_intercept",
        "parameters": {"m": 0.6666666666666666, "b": 1.0, "point": [0.0, 1.0]},
        "answer": "y = 2/3x + 1",
        "alternate_answer": None,
        "solution_text": "A. Given: m = 2/3, point = (0, 1)\nB. Need: slope-intercept form y = mx + b\nC. Formula: y = mx + b\nD. Substitute: 1 = (2/3)(0) + b\nE. Solve: b = 1\nF. Final: y = 2/3x + 1",
        "real_life_text": "Imagine a gentle ramp starting at 1 meter high. For every 3 meters forward, you rise 2 meters. The slope 2/3 tells you the ramp is moderately steep.",
        "real_life_text_tr": "1 metre yuksekliginden baslayan hafif bir rampa dusun. Her 3 metre ileri gittiginde 2 metre yukselirsin. Egim 2/3, rampanin orta derecede dik oldugunu soyler.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    # =================================================================
    # B. Point-Slope (3)
    # =================================================================
    {
        "id": "emb_alg1_point_slope_001",
        "source_type": "embedded",
        "title": "Algebra 1 — Point-slope: m = -1/4, point = (-6, 1)",
        "course": "Algebra (course notes)",
        "section": "Functions and graphing — Point-slope and slope-intercept forms",
        "source_pdf": "Algebra/01 Algebra 1/02 Notes/Notes by section/05 Functions and graphing/03 Point-slope and slope-intercept forms of a line.pdf",
        "page_number": 2,
        "question_text": "Write the equation of the line in point-slope form. m = -1/4, point = (-6, 1)",
        "normalized_question": "Write the equation of the line in point-slope form.\nm = -1/4\npoint = (-6, 1)",
        "problem_type": "point_slope",
        "parameters": {"m": -0.25, "point": [-6.0, 1.0], "b": -0.5},
        "answer": "y - 1 = -1/4(x + 6)",
        "alternate_answer": "y = -1/4x - 1/2",
        "solution_text": "A. Given: m = -1/4 and point = (-6, 1)\nB. Need: point-slope form, then slope-intercept form\nC. Formula: y - y1 = m(x - x1)\nD. Substitute: y - 1 = -1/4(x - (-6))\nE. Simplify: y - 1 = -1/4(x + 6)\nF. Slope-intercept: y = -1/4x - 1/2",
        "real_life_text": "The line goes downward as you move to the right. Since the slope is -1/4, for every 4 units to the right, the line goes down 1 unit.",
        "real_life_text_tr": "Bu dogru saga dogru gidildikce asagi iner. Egim -1/4 oldugu icin her 4 birim saga gidildiginde 1 birim asagi inilir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "emb_alg1_point_slope_002",
        "source_type": "embedded",
        "title": "Algebra 1 — Point-slope: m = 3, point = (2, 5)",
        "course": "Algebra (course notes)",
        "section": "Functions and graphing — Point-slope and slope-intercept forms",
        "source_pdf": "Algebra/01 Algebra 1/02 Notes/Notes by section/05 Functions and graphing/03 Point-slope and slope-intercept forms of a line.pdf",
        "page_number": 1,
        "question_text": "Write the point-slope form of the line with slope 3 passing through (2, 5).",
        "normalized_question": "Write the point-slope form of the line with slope 3 passing through (2, 5).",
        "problem_type": "point_slope",
        "parameters": {"m": 3.0, "point": [2.0, 5.0], "b": -1.0},
        "answer": "y - 5 = 3(x - 2)",
        "alternate_answer": "y = 3x - 1",
        "solution_text": "A. Given: m = 3 and point = (2, 5)\nB. Need: point-slope form, then slope-intercept form\nC. Formula: y - y1 = m(x - x1)\nD. Substitute: y - 5 = 3(x - 2)\nE. Slope-intercept: y = 3x - 1",
        "real_life_text": "You are standing at a point on a hill. Your location is (2, 5). The hill rises at a slope of 3 for every 1 unit forward. Point-slope tells you the path from where you stand; slope-intercept tells you the hill's overall shape.",
        "real_life_text_tr": "Bir tepenin uzerinde bir noktada duruyorsun. Konumun (2, 5). Tepe her 1 birim ileride 3 egimle yukseliyor. Nokta-egim formu durdugun yerden gidişi anlatir; egim-kesme formu tepenin genel seklini soyler.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "emb_alg1_point_slope_003",
        "source_type": "embedded",
        "title": "Algebra 1 — Point-slope: m = -2, point = (3, -4)",
        "course": "Algebra (course notes)",
        "section": "Functions and graphing — Point-slope and slope-intercept forms",
        "source_pdf": "Algebra/01 Algebra 1/02 Notes/Notes by section/05 Functions and graphing/03 Point-slope and slope-intercept forms of a line.pdf",
        "page_number": 2,
        "question_text": "Find the point-slope form of the line with slope -2 passing through (3, -4).",
        "normalized_question": "Find the point-slope form of the line with slope -2 passing through (3, -4).",
        "problem_type": "point_slope",
        "parameters": {"m": -2.0, "point": [3.0, -4.0], "b": 2.0},
        "answer": "y + 4 = -2(x - 3)",
        "alternate_answer": "y = -2x + 2",
        "solution_text": "A. Given: m = -2 and point = (3, -4)\nB. Need: point-slope form, then slope-intercept form\nC. Formula: y - y1 = m(x - x1)\nD. Substitute: y - (-4) = -2(x - 3)\nE. Simplify: y + 4 = -2(x - 3)\nF. Slope-intercept: y = -2x + 2",
        "real_life_text": "The line goes downward as you move to the right. Since the slope is -2, for every 1 unit to the right, the line goes down 2 units.",
        "real_life_text_tr": "Bu dogru saga dogru gidildikce asagi iner. Egim -2 oldugu icin her 1 birim saga gidildiginde 2 birim asagi inilir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    # =================================================================
    # C. Two-Point Line (2)
    # =================================================================
    {
        "id": "emb_alg1_two_point_001",
        "source_type": "embedded",
        "title": "Algebra 1 — Two-point line: (1, 2) and (5, 4)",
        "course": "Algebra (course notes)",
        "section": "Functions and graphing — Graphing linear equations",
        "source_pdf": "Algebra/01 Algebra 1/02 Notes/Notes by section/05 Functions and graphing/04 Graphing linear equations.pdf",
        "page_number": 1,
        "question_text": "Find the equation of the line passing through (1, 2) and (5, 4).",
        "normalized_question": "Find the equation of the line passing through (1, 2) and (5, 4).",
        "problem_type": "two_point_line",
        "parameters": {"p1": [1.0, 2.0], "p2": [5.0, 4.0], "m": 0.5, "b": 1.5},
        "answer": "y = 1/2x + 3/2",
        "alternate_answer": None,
        "solution_text": "A. Given: point1 = (1, 2), point2 = (5, 4)\nB. Need: slope-intercept equation of the line through these two points\nC. Formula: m = (y2 - y1) / (x2 - x1), then b = y1 - m*x1\nD. Substitute: m = (4 - 2) / (5 - 1) = 1/2\nE. Solve: b = 2 - (1/2)(1) = 3/2\nF. Final: y = 1/2x + 3/2",
        "real_life_text": "Imagine two points on a hiking trail. Start at (1, 2) and end at (5, 4). The slope of the trail is 1/2, meaning the trail rises 1/2 unit for every 1 unit forward. The starting height is 3/2.",
        "real_life_text_tr": "Bir yuruyus parkurundaki iki noktayi dusun. (1, 2) noktasindan basla, (5, 4) noktasinda bitir. Parkurun egimi 1/2; yani her 1 birim ileri gidişte 1/2 birim yukselir. Baslangic yuksekligi 3/2.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "emb_alg1_two_point_002",
        "source_type": "embedded",
        "title": "Algebra 1 — Two-point line: (-2, 3) and (4, -1)",
        "course": "Algebra (course notes)",
        "section": "Functions and graphing — Graphing linear equations",
        "source_pdf": "Algebra/01 Algebra 1/02 Notes/Notes by section/05 Functions and graphing/04 Graphing linear equations.pdf",
        "page_number": 2,
        "question_text": "Find the equation of the line passing through (-2, 3) and (4, -1).",
        "normalized_question": "Find the equation of the line passing through (-2, 3) and (4, -1).",
        "problem_type": "two_point_line",
        "parameters": {"p1": [-2.0, 3.0], "p2": [4.0, -1.0], "m": -0.6666666666666666, "b": 1.6666666666666667},
        "answer": "y = -2/3x + 5/3",
        "alternate_answer": None,
        "solution_text": "A. Given: point1 = (-2, 3), point2 = (4, -1)\nB. Need: slope-intercept equation of the line through these two points\nC. Formula: m = (y2 - y1) / (x2 - x1), then b = y1 - m*x1\nD. Substitute: m = (-1 - 3) / (4 - (-2)) = -4/6 = -2/3\nE. Solve: b = 3 - (-2/3)(-2) = 3 - 4/3 = 5/3\nF. Final: y = -2/3x + 5/3",
        "real_life_text": "Imagine a hiking trail that goes from (-2, 3) down to (4, -1). The trail descends 2/3 unit for every 1 unit forward. The overall starting elevation is 5/3.",
        "real_life_text_tr": "(-2, 3)'ten (4, -1)'e inen bir yuruyus parkuru dusun. Parkur her 1 birim ileri gidişte 2/3 birim asagi iner. Genel baslangic yuksekligi 5/3.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    # =================================================================
    # D. Parallel / Perpendicular (2)
    # =================================================================
    {
        "id": "emb_alg2_parallel_001",
        "source_type": "embedded",
        "title": "Algebra 2 — Parallel line to y = 2x + 1 through (3, 4)",
        "course": "Algebra (course notes)",
        "section": "Graphing — Parallel and perpendicular lines",
        "source_pdf": "Algebra/02 Algebra 2/02 Notes/Notes by section/14 Graphing/01 Parallel and perpendicular lines.pdf",
        "page_number": 1,
        "question_text": "Find the equation of the line parallel to y = 2x + 1 passing through (3, 4).",
        "normalized_question": "Find the equation of the line parallel to y = 2x + 1 passing through (3, 4).",
        "problem_type": "parallel_line",
        "parameters": {"orig_m": 2.0, "orig_b": 1.0, "point": [3.0, 4.0], "new_m": 2.0, "new_b": -2.0},
        "answer": "y = 2x - 2",
        "alternate_answer": None,
        "solution_text": "A. Given: original line y = 2x + 1, point = (3, 4)\nB. Need: parallel line through (3, 4)\nC. Formula: parallel lines have the same slope: m_new = m_orig\nD. Substitute: m_new = 2\nE. Solve: b_new = 4 - 2*3 = -2\nF. Final: y = 2x - 2",
        "real_life_text": "Two parallel roads never meet. One road is y = 2x + 1. The other road is y = 2x - 2. They have the same steepness, so they stay the same distance apart forever.",
        "real_life_text_tr": "Iki paralel yol asla kesişmez. Bir yol y = 2x + 1. Diger yol y = 2x - 2. Ayni dikliğe sahipler, bu yuzden sonsuza dek ayni uzaklikta kalirlar.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "emb_alg2_perpendicular_001",
        "source_type": "embedded",
        "title": "Algebra 2 — Perpendicular line to y = 2x + 1 through (3, 4)",
        "course": "Algebra (course notes)",
        "section": "Graphing — Parallel and perpendicular lines",
        "source_pdf": "Algebra/02 Algebra 2/02 Notes/Notes by section/14 Graphing/01 Parallel and perpendicular lines.pdf",
        "page_number": 2,
        "question_text": "Find the equation of the line perpendicular to y = 2x + 1 passing through (3, 4).",
        "normalized_question": "Find the equation of the line perpendicular to y = 2x + 1 passing through (3, 4).",
        "problem_type": "perpendicular_line",
        "parameters": {"orig_m": 2.0, "orig_b": 1.0, "point": [3.0, 4.0], "new_m": -0.5, "new_b": 5.5},
        "answer": "y = -1/2x + 11/2",
        "alternate_answer": None,
        "solution_text": "A. Given: original line y = 2x + 1, point = (3, 4)\nB. Need: perpendicular line through (3, 4)\nC. Formula: m_perp = -1 / m_orig\nD. Substitute: m_perp = -1 / 2 = -1/2\nE. Solve: b_perp = 4 - (-1/2)*3 = 4 + 3/2 = 11/2\nF. Final: y = -1/2x + 11/2",
        "real_life_text": "A ladder leaning against a wall forms a right angle with the ground. The ground is like the original line (y = 2x + 1). The ladder is like the perpendicular line (y = -1/2x + 11/2). Their slopes are negative reciprocals, so they meet at 90°.",
        "real_life_text_tr": "Bir duvara yaslanan merdiven, zeminle dik aci olusturur. Zemin orijinal dogru gibidir (y = 2x + 1). Merdiven dik dogru gibidir (y = -1/2x + 11/2). Egimleri negatif terstir, bu yuzden 90°'de buluşurlar.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    # =================================================================
    # E. Quadratic (1)
    # =================================================================
    {
        "id": "emb_alg2_quadratic_001",
        "source_type": "embedded",
        "title": "Algebra 2 — Quadratic: y = x² - 4x + 3",
        "course": "Algebra (course notes)",
        "section": "Graphing — Graphing parabolas",
        "source_pdf": "Algebra/02 Algebra 2/02 Notes/Notes by section/14 Graphing/02 Graphing parabolas.pdf",
        "page_number": 1,
        "question_text": "Graph y = x² - 4x + 3. Find the vertex and the roots.",
        "normalized_question": "Graph y = x^2 - 4x + 3. Find the vertex and the roots.",
        "problem_type": "quadratic",
        "parameters": {"a": 1.0, "b": -4.0, "c": 3.0, "expr": "x**2 - 4*x + 3"},
        "answer": "Vertex (2, -1), roots x = 1 and x = 3",
        "alternate_answer": None,
        "solution_text": "A. Given: a = 1, b = -4, c = 3 (y = x² - 4x + 3)\nB. Need: vertex, x-intercepts (roots), and y-intercept\nC. Formula: vertex x = -b / (2a); roots from quadratic formula; y-intercept = (0, c)\nD. Substitute: vertex x = -(-4) / (2*1) = 2\nE. Solve: vertex = (2, -1); roots = 1 and 3; y-intercept = (0, 3)\nF. Final: Vertex (2, -1), roots x = 1 and x = 3, axis of symmetry x = 2",
        "real_life_text": "A parabola shows up everywhere in real life: the path of a ball thrown into the air, the shape of a bridge arch or a water fountain. The vertex (2, -1) is the lowest point and x = 2 is the mirror line.",
        "real_life_text_tr": "Parabol gercek hayatta cok yerde gorulur: havaya atilan bir topun izledigi yol, bir kopru kemeri veya fiskiyeden cikan suyun sekli. Tepe noktasi (2, -1) en alcak noktadir ve x = 2 ayna cizgisidir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    # =================================================================
    # F. System of Equations (1)
    # =================================================================
    {
        "id": "emb_alg1_system_001",
        "source_type": "embedded",
        "title": "Algebra 1 — System: y = 2x + 1 and y = -x + 4",
        "course": "Algebra (course notes)",
        "section": "Systems of equations — Solving systems with substitution",
        "source_pdf": "Algebra/01 Algebra 1/02 Notes/Notes by section/07 Systems of equations/02 Solving systems with substitution.pdf",
        "page_number": 1,
        "question_text": "Solve and graph the system: y = 2x + 1 and y = -x + 4.",
        "normalized_question": "Solve and graph the system: y = 2x + 1 and y = -x + 4.",
        "problem_type": "system_of_equations",
        "parameters": {"lines": [[2.0, 1.0], [-1.0, 4.0]], "ix": 1.0, "iy": 3.0},
        "answer": "(1, 3)",
        "alternate_answer": None,
        "solution_text": "A. Given: Line 1: y = 2x + 1; Line 2: y = -x + 4\nB. Need: intersection point (x, y) that satisfies both equations\nC. Formula: set the two right-hand sides equal: 2x + 1 = -x + 4\nD. Substitute: 2x + 1 = -x + 4\nE. Solve: 3x = 3, so x = 1; then y = 2(1) + 1 = 3\nF. Final: Intersection = (1, 3)",
        "real_life_text": "The intersection of two lines is the moment they become equal: where two pricing plans cost exactly the same, or where two moving objects meet. Here that point is (1, 3).",
        "real_life_text_tr": "Iki dogrunun kesisimi gercek hayatta 'esit olduklari an'dir: iki farkli fiyat planinin ayni tutara geldigi nokta veya iki aracin ayni konuma geldigi an. Burada bu nokta (1, 3).",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    # =================================================================
    # G. Linear Algebra Quizzes (2)
    # =================================================================
    {
        "id": "embedded_linear_algebra_system_substitution_001",
        "source_type": "embedded",
        "title": "Linear Algebra — System by substitution: y = x + 7 and x + 2y = -16",
        "course": "Linear Algebra",
        "topic": "Linear systems in two unknowns",
        "source_pdf": "Linear Algebra.quizzes.pdf",
        "page_number": 2,
        "question_text": "Use substitution to find the unique solution to the linear system.\ny = x + 7\nx + 2y = -16",
        "normalized_question": "Solve and graph the system: y = x + 7 and y = -0.5x - 8.",
        "problem_type": "system_of_equations",
        "parameters": {"lines": [[1.0, 7.0], [-0.5, -8.0]], "ix": -10.0, "iy": -3.0},
        "answer": "(-10, -3)",
        "alternate_answer": None,
        "solution_text": "Substitute y = x + 7 into x + 2y = -16. Then x + 2(x + 7) = -16, so 3x + 14 = -16, 3x = -30, x = -10. Then y = -10 + 7 = -3. The solution is (-10, -3).",
        "real_life_text": "The solution is the point where both linear relationships are true at the same time.",
        "real_life_text_tr": "Cozum, her iki dogrusal iliskinin ayni anda dogru oldugu noktadir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_linear_algebra_system_elimination_001",
        "source_type": "embedded",
        "title": "Linear Algebra — System by elimination: x - 3y = -7 and 2x - 3y = 4",
        "course": "Linear Algebra",
        "topic": "Linear systems in two unknowns",
        "source_pdf": "Linear Algebra.quizzes.pdf",
        "page_number": 3,
        "question_text": "Use elimination to find the unique solution to the system.\nx - 3y = -7\n2x - 3y = 4",
        "normalized_question": "Solve and graph the system: y = 1/3 x + 7/3 and y = 2/3 x - 4/3.",
        "problem_type": "system_of_equations",
        "parameters": {"lines": [[0.3333333333333333, 2.3333333333333335], [0.6666666666666666, -1.3333333333333333]], "ix": 11.0, "iy": 6.0},
        "answer": "(11, 6)",
        "alternate_answer": None,
        "solution_text": "Subtract the first equation from the second: (2x - 3y) - (x - 3y) = 4 - (-7), so x = 11. Substitute x = 11 into the first equation: 11 - 3y = -7, so -3y = -18, y = 6. The solution is (11, 6).",
        "real_life_text": "The solution is the point where both linear relationships are true at the same time.",
        "real_life_text_tr": "Cozum, her iki dogrusal iliskinin ayni anda dogru oldugu noktadir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    # =================================================================
    # H. Geometry Quizzes (4)
    # =================================================================
    {
        "id": "embedded_geometry_distance_3d_001",
        "source_type": "embedded",
        "title": "Geometry — Distance 3D: P1 = (3, 6, 1) and P2 = (0, 1, 5)",
        "course": "Geometry",
        "topic": "Distance formula",
        "source_pdf": "Geometry.quizzes.pdf",
        "page_number": 5,
        "question_text": "Calculate the distance between P1 and P2.\nP1 = (3, 6, 1)\nP2 = (0, 1, 5)",
        "normalized_question": "Calculate the distance between P1 and P2.\nP1 = (3, 6, 1)\nP2 = (0, 1, 5)",
        "problem_type": "geometry_distance_3d",
        "parameters": {"p1": [3.0, 6.0, 1.0], "p2": [0.0, 1.0, 5.0], "distance": 7.0710678118654755},
        "answer": "5*sqrt(2) ≈ 7.07",
        "alternate_answer": "sqrt(50)",
        "solution_text": "d = sqrt((3 - 0)² + (6 - 1)² + (1 - 5)²) = sqrt(9 + 25 + 16) = sqrt(50) = 5*sqrt(2) ≈ 7.07",
        "real_life_text": "The distance between two points in 3D space is like measuring the straight line between two stars in space.",
        "real_life_text_tr": "3D uzayda iki nokta arasindaki mesafe, uzayda iki yildiz arasindaki duz cizgi gibi olcer.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_geometry_midpoint_3d_001",
        "source_type": "embedded",
        "title": "Geometry — Midpoint 3D: P1 = (6, 5, -3), M = (4, -4, -5)",
        "course": "Geometry",
        "topic": "Midpoint formula",
        "source_pdf": "Geometry.quizzes.pdf",
        "page_number": 6,
        "question_text": "Find the coordinates of P2 if P1 = (6, 5, -3) and M = (4, -4, -5) is the midpoint of P1P2.",
        "normalized_question": "Find the coordinates of P2 if P1 = (6, 5, -3) and M = (4, -4, -5) is the midpoint of P1P2.",
        "problem_type": "geometry_midpoint_3d",
        "parameters": {"p1": [6.0, 5.0, -3.0], "midpoint": [4.0, -4.0, -5.0], "p2": [2.0, -13.0, -7.0]},
        "answer": "(2, -13, -7)",
        "alternate_answer": None,
        "solution_text": "M = ((x1+x2)/2, (y1+y2)/2, (z1+z2)/2). So x2 = 2*4 - 6 = 2, y2 = 2*(-4) - 5 = -13, z2 = 2*(-5) - (-3) = -7. P2 = (2, -13, -7).",
        "real_life_text": "If you know one endpoint and the midpoint, you can find the other endpoint by mirroring the distance.",
        "real_life_text_tr": "Bir uc noktayi ve orta noktayi biliyorsaniz, mesafeyi aynalayarak diger uc noktayi bulabilirsiniz.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_geometry_midpoint_2d_001",
        "source_type": "embedded",
        "title": "Geometry — Other endpoint from midpoint: (5, 8) and midpoint (3, 2)",
        "course": "Geometry",
        "topic": "Midpoint formula",
        "source_pdf": "Geometry.quizzes.pdf",
        "page_number": 4,
        "question_text": "A line segment has one endpoint at (5, 8), and its midpoint at (3, 2). Find the position of the other endpoint.",
        "normalized_question": "A line segment has one endpoint at (5, 8), and its midpoint at (3, 2). Find the position of the other endpoint.",
        "problem_type": "geometry_midpoint_2d",
        "parameters": {"p1": [5.0, 8.0], "midpoint": [3.0, 2.0], "p2": [1.0, -4.0]},
        "answer": "(1, -4)",
        "alternate_answer": None,
        "solution_text": "M = ((x1+x2)/2, (y1+y2)/2). So x2 = 2*3 - 5 = 1, y2 = 2*2 - 8 = -4. The other endpoint is (1, -4).",
        "real_life_text": "If you know one endpoint and the midpoint, you can find the other endpoint by mirroring the distance.",
        "real_life_text_tr": "Bir uc noktayi ve orta noktayi biliyorsaniz, mesafeyi aynalayarak diger uc noktayi bulabilirsiniz.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_geometry_distance_2d_001",
        "source_type": "embedded",
        "title": "Geometry — Distance 2D: (1, 2) and (4, 6)",
        "course": "Geometry",
        "topic": "Distance formula",
        "source_pdf": "Geometry.quizzes.pdf",
        "page_number": 4,
        "question_text": "Find the distance between the points (1, 2) and (4, 6).",
        "normalized_question": "Find the distance between the points (1, 2) and (4, 6).",
        "problem_type": "geometry_distance_2d",
        "parameters": {"p1": [1.0, 2.0], "p2": [4.0, 6.0], "distance": 5.0},
        "answer": "5",
        "alternate_answer": None,
        "solution_text": "d = sqrt((1 - 4)² + (2 - 6)²) = sqrt(9 + 16) = sqrt(25) = 5",
        "real_life_text": "The distance between two points on a map is the straight-line distance, like a bird flying directly from one city to another.",
        "real_life_text_tr": "Haritada iki nokta arasindaki mesafe, bir kusun bir sehirden digerine dogrudan ucmesi gibidir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    # =================================================================
    # I. Algebra 2 Quizzes (5)
    # =================================================================
    {
        "id": "embedded_alg2_exponent_negative_base_001",
        "source_type": "embedded",
        "title": "Algebra 2 — Exponent: -3^2",
        "course": "Algebra 2",
        "topic": "Powers of negative bases",
        "source_pdf": "Algebra 2.quizzes.pdf",
        "page_number": 1,
        "question_text": "Simplify the expression.\n-3^2",
        "normalized_question": "Simplify the expression.\n-3^2",
        "problem_type": "exponent_negative_base",
        "parameters": {"base": 3, "exponent": 2, "result": -9, "note": "-(3^2) = -9, not (-3)^2 = 9"},
        "answer": "-9",
        "alternate_answer": None,
        "solution_text": "-3^2 = -(3^2) = -(9) = -9. This is different from (-3)^2 = 9. Without parentheses, the exponent applies only to 3, then the negative sign is applied.",
        "real_life_text": "Order of operations matters! The exponent is evaluated before the negative sign when there are no parentheses.",
        "real_life_text_tr": "Islem sirasi onemlidir! Parantez yoksa, us isareti negatif isaretten once degerlendirilir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_alg2_exponent_fractional_001",
        "source_type": "embedded",
        "title": "Algebra 2 — Fractional exponent: 8^(2/3)",
        "course": "Algebra 2",
        "topic": "Fractional exponents",
        "source_pdf": "Algebra 2.quizzes.pdf",
        "page_number": 5,
        "question_text": "Simplify 8^(2/3).",
        "normalized_question": "Simplify 8^(2/3).",
        "problem_type": "exponent_fractional",
        "parameters": {"base": 8, "numerator": 2, "denominator": 3, "result": 4},
        "answer": "4",
        "alternate_answer": None,
        "solution_text": "8^(2/3) = (cube root of 8)^2 = 2^2 = 4. Or equivalently, 8^(2/3) = (8^2)^(1/3) = 64^(1/3) = 4.",
        "real_life_text": "A fractional exponent is both a power and a root. The denominator tells you the root, the numerator tells you the power.",
        "real_life_text_tr": "Kesirli us hem bir kuvvet hem de bir koku temsil eder. Payda koku soyler, pay kuvveti soyler.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_alg2_exponent_negative_001",
        "source_type": "embedded",
        "title": "Algebra 2 — Negative exponent: 2^(-3)",
        "course": "Algebra 2",
        "topic": "Negative exponents",
        "source_pdf": "Algebra 2.quizzes.pdf",
        "page_number": 4,
        "question_text": "Simplify 2^(-3).",
        "normalized_question": "Simplify 2^(-3).",
        "problem_type": "exponent_negative",
        "parameters": {"base": 2, "exponent": -3, "result": 0.125},
        "answer": "1/8",
        "alternate_answer": "0.125",
        "solution_text": "2^(-3) = 1 / 2^3 = 1 / 8 = 0.125. A negative exponent means taking the reciprocal.",
        "real_life_text": "A negative exponent flips the number into a fraction. It is the opposite of a positive exponent.",
        "real_life_text_tr": "Negatif us, sayiyi bir kesir olarak cevirir. Pozitif usun tersidir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_alg2_rationalize_001",
        "source_type": "embedded",
        "title": "Algebra 2 — Rationalize: 1/(2 + sqrt(3))",
        "course": "Algebra 2",
        "topic": "Rationalizing denominator",
        "source_pdf": "Algebra 2.quizzes.pdf",
        "page_number": 7,
        "question_text": "Rationalize the denominator: 1 / (2 + sqrt(3))",
        "normalized_question": "Rationalize the denominator: 1 / (2 + sqrt(3))",
        "problem_type": "rationalize",
        "parameters": {"numerator": 1, "denominator": "2 + sqrt(3)", "result": "2 - sqrt(3)"},
        "answer": "2 - sqrt(3)",
        "alternate_answer": None,
        "solution_text": "Multiply numerator and denominator by the conjugate (2 - sqrt(3)): (1 * (2 - sqrt(3))) / ((2 + sqrt(3))(2 - sqrt(3))) = (2 - sqrt(3)) / (4 - 3) = 2 - sqrt(3).",
        "real_life_text": "Rationalizing removes the radical from the denominator using the conjugate, which is the same binomial with the opposite sign.",
        "real_life_text_tr": "Rasyonellestirme, paydadan koku eslenigi (terst isaretli ayni binom) kullanarak kaldirir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_alg2_percent_markdown_001",
        "source_type": "embedded",
        "title": "Algebra 2 — Percent markdown: $58 at 75% off",
        "course": "Algebra 2",
        "topic": "Percent markdown",
        "source_pdf": "Algebra 2.quizzes.pdf",
        "page_number": 10,
        "question_text": "The price of a bicycle was marked down to $58.00, and the sale price was 75% off of the original price. What was the original price?",
        "normalized_question": "The price of a bicycle was marked down to $58.00, and the sale price was 75% off of the original price. What was the original price?",
        "problem_type": "percent_markdown",
        "parameters": {"sale_price": 58.0, "discount_percent": 75.0, "original_price": 232.0},
        "answer": "$232",
        "alternate_answer": None,
        "solution_text": "$58 is 25% of the original price (100% - 75% = 25%). Original = 58 / 0.25 = 232. The original price was $232.",
        "real_life_text": "If something is 75% off, you pay only 25% of the original price. To find the original, divide the sale price by the remaining percentage.",
        "real_life_text_tr": "Bir sey %75 indirimliyse, orijinal fiyatin sadece %25'ini odersiniz. Orijinal fiyati bulmak icin satis fiyatini kalan yuzdeye bolun.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    # =================================================================
    # J. Pre-Algebra Quizzes (5)
    # =================================================================
    {
        "id": "embedded_prealgebra_number_sets_natural_001",
        "source_type": "embedded",
        "title": "Pre-Algebra — Number sets: counting numbers",
        "course": "Pre-Algebra",
        "topic": "Number sets",
        "source_pdf": "Pre-Algebra.quizzes.pdf",
        "page_number": 1,
        "question_text": "Which of the following is another name for the counting numbers?",
        "normalized_question": "Which of the following is another name for the counting numbers?",
        "problem_type": "concept_card_number_sets",
        "parameters": {"answer": "natural numbers"},
        "answer": "Natural numbers",
        "alternate_answer": None,
        "solution_text": "Counting numbers are also called natural numbers: {1, 2, 3, 4, ...}. They are the positive integers starting from 1.",
        "real_life_text": "Natural numbers are the numbers we use to count objects: 1 apple, 2 apples, 3 apples...",
        "real_life_text_tr": "Dogal sayilar, nesneleri saymak icin kullandigimiz sayilardir: 1 elma, 2 elma, 3 elma...",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_prealgebra_number_sets_whole_001",
        "source_type": "embedded",
        "title": "Pre-Algebra — Number sets: whole numbers",
        "course": "Pre-Algebra",
        "topic": "Number sets",
        "source_pdf": "Pre-Algebra.quizzes.pdf",
        "page_number": 1,
        "question_text": "Which set could represent whole numbers?",
        "normalized_question": "Which set could represent whole numbers?",
        "problem_type": "concept_card_number_sets",
        "parameters": {"answer": "{0, 1, 2, 3, ...}"},
        "answer": "{0, 1, 2, 3, ...}",
        "alternate_answer": None,
        "solution_text": "Whole numbers include zero and all natural numbers: {0, 1, 2, 3, ...}. They are the non-negative integers.",
        "real_life_text": "Whole numbers are the numbers we use when counting including zero: 0 apples, 1 apple, 2 apples...",
        "real_life_text_tr": "Tam sayilar, sifiri da iceren sayma sayilaridir: 0 elma, 1 elma, 2 elma...",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_prealgebra_identity_addition_001",
        "source_type": "embedded",
        "title": "Pre-Algebra — Identity number for addition",
        "course": "Pre-Algebra",
        "topic": "Identity numbers",
        "source_pdf": "Pre-Algebra.quizzes.pdf",
        "page_number": 4,
        "question_text": "What is the identity number for addition?",
        "normalized_question": "What is the identity number for addition?",
        "problem_type": "concept_card_identity_numbers",
        "parameters": {"answer": 0},
        "answer": "0",
        "alternate_answer": None,
        "solution_text": "The identity number for addition is 0, because adding 0 to any number leaves it unchanged: a + 0 = a.",
        "real_life_text": "Adding zero to anything does not change it. Zero is the 'do nothing' number for addition.",
        "real_life_text_tr": "Sifir eklemek hicbir seyi degistirmez. Sifir, toplama icin 'hicbir sey yapma' sayisidir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_prealgebra_pemdas_001",
        "source_type": "embedded",
        "title": "Pre-Algebra — Order of operations: 3 + 4 * 2",
        "course": "Pre-Algebra",
        "topic": "Order of operations",
        "source_pdf": "Pre-Algebra.quizzes.pdf",
        "page_number": 5,
        "question_text": "Evaluate the expression.\n3 + 4 * 2",
        "normalized_question": "Evaluate the expression.\n3 + 4 * 2",
        "problem_type": "pemdas",
        "parameters": {"expression": "3 + 4 * 2", "result": 11},
        "answer": "11",
        "alternate_answer": None,
        "solution_text": "Using PEMDAS: Multiplication before Addition. 4 * 2 = 8, then 3 + 8 = 11.",
        "real_life_text": "Order of operations is like a recipe: you must follow the steps in the right order to get the correct answer.",
        "real_life_text_tr": "Islem sirasi bir tarif gibidir: dogru cevabi almak icin adimlari dogru sirada izlemelisiniz.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_prealgebra_percent_decimal_001",
        "source_type": "embedded",
        "title": "Pre-Algebra — Percent to decimal: 25%",
        "course": "Pre-Algebra",
        "topic": "Percent basics",
        "source_pdf": "Pre-Algebra.quizzes.pdf",
        "page_number": 7,
        "question_text": "Convert 25% to a decimal.",
        "normalized_question": "Convert 25% to a decimal.",
        "problem_type": "percent_conversion",
        "parameters": {"percent": 25, "decimal": 0.25},
        "answer": "0.25",
        "alternate_answer": None,
        "solution_text": "25% = 25 / 100 = 0.25. To convert a percent to a decimal, divide by 100.",
        "real_life_text": "Percent means 'per hundred'. 25% is 25 out of 100, which is 0.25.",
        "real_life_text_tr": "Yuzde 'yuzde' demektir. %25, 100'de 25'tir, yani 0.25.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    # =================================================================
    # K. Algebra 1 Quizzes (5)
    # =================================================================
    {
        "id": "embedded_alg1_variables_001",
        "source_type": "embedded",
        "title": "Algebra 1 — Identify the variable in 3x + 2",
        "course": "Algebra 1",
        "topic": "Variables",
        "source_pdf": "Algebra 1.quizzes.pdf",
        "page_number": 1,
        "question_text": "In the expression 3x + 2, what is the variable?",
        "normalized_question": "In the expression 3x + 2, what is the variable?",
        "problem_type": "concept_card_variables",
        "parameters": {"expression": "3x + 2", "variable": "x"},
        "answer": "x",
        "alternate_answer": None,
        "solution_text": "The variable is the letter that represents an unknown quantity. In 3x + 2, the variable is x.",
        "real_life_text": "A variable is like a container that can hold different numbers. In 3x + 2, x is the container.",
        "real_life_text_tr": "Degisken, farkli sayilari tutabilen bir kutu gibidir. 3x + 2'de x, kutudur.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_alg1_coefficients_001",
        "source_type": "embedded",
        "title": "Algebra 1 — Coefficient of x in -5x",
        "course": "Algebra 1",
        "topic": "Coefficients",
        "source_pdf": "Algebra 1.quizzes.pdf",
        "page_number": 1,
        "question_text": "What is the coefficient of x in the term -5x?",
        "normalized_question": "What is the coefficient of x in the term -5x?",
        "problem_type": "concept_card_coefficients",
        "parameters": {"term": "-5x", "coefficient": -5},
        "answer": "-5",
        "alternate_answer": None,
        "solution_text": "The coefficient is the numerical factor multiplied by the variable. In -5x, the coefficient is -5.",
        "real_life_text": "The coefficient is like the multiplier that tells you how many of the variable you have. In -5x, you have negative five x's.",
        "real_life_text_tr": "Katsayi, degiskenden kac tane oldugunu soyleyen carpandir. -5x'te, eksi bes x'iniz vardir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_alg1_distributive_001",
        "source_type": "embedded",
        "title": "Algebra 1 — Expand 3(x + 4)",
        "course": "Algebra 1",
        "topic": "Distributive Property",
        "source_pdf": "Algebra 1.quizzes.pdf",
        "page_number": 3,
        "question_text": "Expand 3(x + 4).",
        "normalized_question": "Expand 3(x + 4).",
        "problem_type": "distributive",
        "parameters": {"a": 3, "b": 1, "c": 4, "result": "3x + 12"},
        "answer": "3x + 12",
        "alternate_answer": None,
        "solution_text": "Using the distributive property: 3(x + 4) = 3*x + 3*4 = 3x + 12.",
        "real_life_text": "Distributive property is like giving 3 candies to each person in a group of x people and 4 people separately.",
        "real_life_text_tr": "Dagilma ozelligi, x kisilik bir gruptaki ve 4 kisilik ayrı bir gruptaki her kisiye 3 seker vermek gibidir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_alg1_solve_linear_001",
        "source_type": "embedded",
        "title": "Algebra 1 — Solve 2x + 5 = 13",
        "course": "Algebra 1",
        "topic": "Linear equations",
        "source_pdf": "Algebra 1.quizzes.pdf",
        "page_number": 4,
        "question_text": "Solve for x: 2x + 5 = 13",
        "normalized_question": "Solve for x: 2x + 5 = 13",
        "problem_type": "linear_equation",
        "parameters": {"a": 2, "b": 5, "c": 13, "result": 4},
        "answer": "x = 4",
        "alternate_answer": None,
        "solution_text": "2x + 5 = 13. Subtract 5 from both sides: 2x = 8. Divide by 2: x = 4.",
        "real_life_text": "Solving an equation is like balancing a scale. Whatever you do to one side, you must do to the other.",
        "real_life_text_tr": "Bir denklemi cozmek, bir teraziyi dengelemek gibidir. Bir tarafa ne yaparsaniz, diger tarafa da yapmalisiniz.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_alg1_function_eval_001",
        "source_type": "embedded",
        "title": "Algebra 1 — Evaluate f(3) if f(x) = 2x + 1",
        "course": "Algebra 1",
        "topic": "Function notation",
        "source_pdf": "Algebra 1.quizzes.pdf",
        "page_number": 7,
        "question_text": "Evaluate f(3) if f(x) = 2x + 1.",
        "normalized_question": "Evaluate f(3) if f(x) = 2x + 1.",
        "problem_type": "function_evaluation",
        "parameters": {"function": "2x + 1", "input": 3, "result": 7},
        "answer": "7",
        "alternate_answer": None,
        "solution_text": "f(3) = 2(3) + 1 = 6 + 1 = 7. Replace x with 3 and evaluate.",
        "real_life_text": "Evaluating a function is like using a machine: you put in a number (3), the machine follows the rule (2x+1), and gives you a result (7).",
        "real_life_text_tr": "Bir fonksiyonu degerlendirmek, bir makine kullanmak gibidir: bir sayi koyarsiniz (3), makine kurali izler (2x+1) ve sonuc verir (7).",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    # =================================================================
    # L. Geometry extra (4)
    # =================================================================
    {
        "id": "embedded_geometry_pythagorean_001",
        "source_type": "embedded",
        "title": "Geometry — Pythagorean Theorem: a = 3, b = 4",
        "course": "Geometry",
        "topic": "Triangles",
        "source_pdf": "Geometry.quizzes.pdf",
        "page_number": 12,
        "question_text": "If a = 3 and b = 4 in a right triangle, what is c?",
        "normalized_question": "If a = 3 and b = 4 in a right triangle, what is c?",
        "problem_type": "pythagorean",
        "parameters": {"a": 3, "b": 4, "c": 5},
        "answer": "5",
        "alternate_answer": None,
        "solution_text": "c² = a² + b² = 3² + 4² = 9 + 16 = 25. So c = sqrt(25) = 5.",
        "real_life_text": "The Pythagorean theorem is used to find the diagonal of a rectangle or the shortest distance between two points.",
        "real_life_text_tr": "Pisagor teoremi, bir dikdortgenin kosegenini bulmak veya iki nokta arasindaki en kisa mesafeyi bulmak icin kullanilir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_geometry_triangle_area_001",
        "source_type": "embedded",
        "title": "Geometry — Triangle area: base 6, height 4",
        "course": "Geometry",
        "topic": "Triangles",
        "source_pdf": "Geometry.quizzes.pdf",
        "page_number": 13,
        "question_text": "Find the area of a triangle with base 6 and height 4.",
        "normalized_question": "Find the area of a triangle with base 6 and height 4.",
        "problem_type": "triangle_area",
        "parameters": {"base": 6, "height": 4, "area": 12},
        "answer": "12",
        "alternate_answer": None,
        "solution_text": "A = 1/2 * b * h = 1/2 * 6 * 4 = 12.",
        "real_life_text": "The area of a triangle is half the area of a rectangle with the same base and height.",
        "real_life_text_tr": "Bir ucgenin alani, ayni taban ve yukseklige sahip bir dikdortgenin alaninin yarisidir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_geometry_circle_area_001",
        "source_type": "embedded",
        "title": "Geometry — Circle area: radius 3",
        "course": "Geometry",
        "topic": "Circles",
        "source_pdf": "Geometry.quizzes.pdf",
        "page_number": 14,
        "question_text": "Find the area of a circle with radius 3.",
        "normalized_question": "Find the area of a circle with radius 3.",
        "problem_type": "circle_area",
        "parameters": {"radius": 3, "area": 28.274333882308138},
        "answer": "9*pi ≈ 28.27",
        "alternate_answer": None,
        "solution_text": "A = pi * r² = pi * 3² = 9*pi ≈ 28.27.",
        "real_life_text": "The area of a circle is the space inside it. A larger radius means a much larger area.",
        "real_life_text_tr": "Bir dairenin alani, icindeki bosluktur. Daha buyuk yaricap, cok daha buyuk bir alan demektir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_geometry_circumference_001",
        "source_type": "embedded",
        "title": "Geometry — Circumference: radius 5",
        "course": "Geometry",
        "topic": "Circles",
        "source_pdf": "Geometry.quizzes.pdf",
        "page_number": 14,
        "question_text": "Find the circumference of a circle with radius 5.",
        "normalized_question": "Find the circumference of a circle with radius 5.",
        "problem_type": "circle_circumference",
        "parameters": {"radius": 5, "circumference": 31.41592653589793},
        "answer": "10*pi ≈ 31.42",
        "alternate_answer": None,
        "solution_text": "C = 2*pi*r = 2*pi*5 = 10*pi ≈ 31.42.",
        "real_life_text": "The circumference is the distance around a circle. It is like measuring the edge of a wheel.",
        "real_life_text_tr": "Cevre, bir dairenin etrafindaki mesafedir. Bir tekerlegin kenarini olcmek gibidir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    # =================================================================
    # M. Linear Algebra extra (4)
    # =================================================================
    {
        "id": "embedded_linalg_matrix_add_001",
        "source_type": "embedded",
        "title": "Linear Algebra — Matrix addition: [[1,2],[3,4]] + [[5,6],[7,8]]",
        "course": "Linear Algebra",
        "topic": "Matrix addition",
        "source_pdf": "Linear Algebra.quizzes.pdf",
        "page_number": 6,
        "question_text": "Add the matrices [[1, 2], [3, 4]] and [[5, 6], [7, 8]].",
        "normalized_question": "Add the matrices [[1, 2], [3, 4]] and [[5, 6], [7, 8]].",
        "problem_type": "matrix_addition",
        "parameters": {"m1": [[1, 2], [3, 4]], "m2": [[5, 6], [7, 8]], "result": [[6, 8], [10, 12]]},
        "answer": "[[6, 8], [10, 12]]",
        "alternate_answer": None,
        "solution_text": "Add corresponding entries: 1+5=6, 2+6=8, 3+7=10, 4+8=12. Result: [[6, 8], [10, 12]].",
        "real_life_text": "Matrix addition is like combining two tables of data by adding matching cells.",
        "real_life_text_tr": "Matris toplami, iki veri tablosunu eslestirilen hucreleri ekleyerek birlestirmek gibidir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_linalg_scalar_mult_001",
        "source_type": "embedded",
        "title": "Linear Algebra — Scalar multiplication: 3 * [[1,2],[3,4]]",
        "course": "Linear Algebra",
        "topic": "Scalar multiplication",
        "source_pdf": "Linear Algebra.quizzes.pdf",
        "page_number": 6,
        "question_text": "Multiply 3 * [[1, 2], [3, 4]].",
        "normalized_question": "Multiply 3 * [[1, 2], [3, 4]].",
        "problem_type": "scalar_multiplication",
        "parameters": {"scalar": 3, "matrix": [[1, 2], [3, 4]], "result": [[3, 6], [9, 12]]},
        "answer": "[[3, 6], [9, 12]]",
        "alternate_answer": None,
        "solution_text": "Multiply every entry by 3: 3*1=3, 3*2=6, 3*3=9, 3*4=12. Result: [[3, 6], [9, 12]].",
        "real_life_text": "Scalar multiplication is like scaling every value in a table by the same factor.",
        "real_life_text_tr": "Skaler carpma, bir tablodaki her degeri ayni faktorle olceklendirmek gibidir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_linalg_determinant_001",
        "source_type": "embedded",
        "title": "Linear Algebra — Determinant of [[2,3],[4,5]]",
        "course": "Linear Algebra",
        "topic": "Determinants",
        "source_pdf": "Linear Algebra.quizzes.pdf",
        "page_number": 8,
        "question_text": "Find the determinant of [[2, 3], [4, 5]].",
        "normalized_question": "Find the determinant of [[2, 3], [4, 5]].",
        "problem_type": "determinant_2x2",
        "parameters": {"a": 2, "b": 3, "c": 4, "d": 5, "result": -2},
        "answer": "-2",
        "alternate_answer": None,
        "solution_text": "det = ad - bc = (2)(5) - (3)(4) = 10 - 12 = -2.",
        "real_life_text": "The determinant tells you if a matrix can be inverted. Zero means no inverse exists.",
        "real_life_text_tr": "Determinant, bir matrisin tersinin alinip alinamayacagini soyler. Sifir, tersinin olmadigi anlamina gelir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_linalg_inverse_001",
        "source_type": "embedded",
        "title": "Linear Algebra — Inverse of [[1,2],[3,4]]",
        "course": "Linear Algebra",
        "topic": "Inverse matrices",
        "source_pdf": "Linear Algebra.quizzes.pdf",
        "page_number": 8,
        "question_text": "Find the inverse of [[1, 2], [3, 4]].",
        "normalized_question": "Find the inverse of [[1, 2], [3, 4]].",
        "problem_type": "inverse_2x2",
        "parameters": {"a": 1, "b": 2, "c": 3, "d": 4, "det": -2, "result": [[-2, 1], [1.5, -0.5]]},
        "answer": "[[-2, 1], [3/2, -1/2]]",
        "alternate_answer": None,
        "solution_text": "det = (1)(4) - (2)(3) = -2. A^(-1) = (1/det) * [[d, -b], [-c, a]] = (-1/2) * [[4, -2], [-3, 1]] = [[-2, 1], [3/2, -1/2]].",
        "real_life_text": "The inverse of a matrix is like the 'undo' button for matrix multiplication.",
        "real_life_text_tr": "Bir matrisin tersi, matris carpma islemi icin 'geri al' dugmesi gibidir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    # =================================================================
    # N. Algebra 2 extra (3)
    # =================================================================
    {
        "id": "embedded_alg2_zero_exponent_001",
        "source_type": "embedded",
        "title": "Algebra 2 — Zero exponent: 5^0",
        "course": "Algebra 2",
        "topic": "Zero exponent",
        "source_pdf": "Algebra 2.quizzes.pdf",
        "page_number": 3,
        "question_text": "What is 5^0?",
        "normalized_question": "What is 5^0?",
        "problem_type": "zero_exponent",
        "parameters": {"base": 5, "exponent": 0, "result": 1},
        "answer": "1",
        "alternate_answer": None,
        "solution_text": "Any nonzero number raised to the power of 0 equals 1. So 5^0 = 1.",
        "real_life_text": "Raising to the power of zero is like doing nothing to the number except turning it into 1.",
        "real_life_text_tr": "Sifirinci kuvvete yukseltmek, sayiya hicbir sey yapmadan 1'e cevirmek gibidir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_alg2_logarithm_001",
        "source_type": "embedded",
        "title": "Algebra 2 — Logarithm: log_2(8)",
        "course": "Algebra 2",
        "topic": "Logarithms",
        "source_pdf": "Algebra 2.quizzes.pdf",
        "page_number": 9,
        "question_text": "Evaluate log_2(8).",
        "normalized_question": "Evaluate log_2(8).",
        "problem_type": "logarithm",
        "parameters": {"base": 2, "argument": 8, "result": 3},
        "answer": "3",
        "alternate_answer": None,
        "solution_text": "log_2(8) = 3 because 2^3 = 8. A logarithm asks: 'To what power must the base be raised to get the argument?'",
        "real_life_text": "A logarithm is the inverse of an exponent. If 2^3 = 8, then log_2(8) = 3.",
        "real_life_text_tr": "Logaritma, bir usun tersidir. 2^3 = 8 ise, log_2(8) = 3'tur.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_alg2_complex_number_001",
        "source_type": "embedded",
        "title": "Algebra 2 — Complex number: real part of 3 + 4i",
        "course": "Algebra 2",
        "topic": "Complex numbers",
        "source_pdf": "Algebra 2.quizzes.pdf",
        "page_number": 11,
        "question_text": "What is the real part of 3 + 4i?",
        "normalized_question": "What is the real part of 3 + 4i?",
        "problem_type": "complex_number",
        "parameters": {"real": 3, "imaginary": 4, "result": 3},
        "answer": "3",
        "alternate_answer": None,
        "solution_text": "In the complex number a + bi, a is the real part and b is the imaginary part. For 3 + 4i, the real part is 3.",
        "real_life_text": "Complex numbers have two parts: a real part (like the x-coordinate) and an imaginary part (like the y-coordinate).",
        "real_life_text_tr": "Karmasik sayilarin iki bolumu vardir: gercek bolum (x koordinati gibi) ve sanal bolum (y koordinati gibi).",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    # =================================================================
    # O. Pre-Algebra extra (3)
    # =================================================================
    {
        "id": "embedded_prealgebra_absolute_value_001",
        "source_type": "embedded",
        "title": "Pre-Algebra — Absolute value of -7",
        "course": "Pre-Algebra",
        "topic": "Absolute value",
        "source_pdf": "Pre-Algebra.quizzes.pdf",
        "page_number": 5,
        "question_text": "What is the absolute value of -7?",
        "normalized_question": "What is the absolute value of -7?",
        "problem_type": "absolute_value",
        "parameters": {"value": -7, "result": 7},
        "answer": "7",
        "alternate_answer": None,
        "solution_text": "|-7| = 7. The absolute value is the distance from zero, which is always non-negative.",
        "real_life_text": "Absolute value is like measuring distance without caring about direction. Walking 7 meters east or 7 meters west is the same distance.",
        "real_life_text_tr": "Mutlak deger, yonu umursamadan mesafe olcmek gibidir. 7 metre doguya veya 7 metre batiya yurumek ayni mesafedir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_prealgebra_fraction_add_001",
        "source_type": "embedded",
        "title": "Pre-Algebra — Add 1/2 + 1/3",
        "course": "Pre-Algebra",
        "topic": "Fractions",
        "source_pdf": "Pre-Algebra.quizzes.pdf",
        "page_number": 6,
        "question_text": "Add 1/2 + 1/3.",
        "normalized_question": "Add 1/2 + 1/3.",
        "problem_type": "fraction_addition",
        "parameters": {"a": 1, "b": 2, "c": 1, "d": 3, "result": "5/6"},
        "answer": "5/6",
        "alternate_answer": None,
        "solution_text": "1/2 + 1/3 = (1*3 + 1*2) / (2*3) = (3 + 2) / 6 = 5/6.",
        "real_life_text": "Adding fractions is like combining parts of different sizes. You need to make the pieces the same size first.",
        "real_life_text_tr": "Kesirleri toplamak, farkli boyutlardaki parcalari birlestirmek gibidir. Once parcalari ayni boyuta getirmelisiniz.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_prealgebra_set_subset_001",
        "source_type": "embedded",
        "title": "Pre-Algebra — Is {1,2} a subset of {1,2,3}?",
        "course": "Pre-Algebra",
        "topic": "Set notation",
        "source_pdf": "Pre-Algebra.quizzes.pdf",
        "page_number": 3,
        "question_text": "Is {1, 2} a subset of {1, 2, 3}?",
        "normalized_question": "Is {1, 2} a subset of {1, 2, 3}?",
        "problem_type": "set_subset",
        "parameters": {"set_a": [1, 2], "set_b": [1, 2, 3], "result": True},
        "answer": "Yes",
        "alternate_answer": None,
        "solution_text": "Yes, {1, 2} is a subset of {1, 2, 3} because every element of {1, 2} is also in {1, 2, 3}.",
        "real_life_text": "A subset is like a smaller group that fits entirely inside a larger group.",
        "real_life_text_tr": "Bir alt kume, daha buyuk bir grubun tamamen icine sigan daha kucuk bir gruptur.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    # =================================================================
    # P. Algebra 1 extra (3)
    # =================================================================
    {
        "id": "embedded_alg1_quadratic_formula_001",
        "source_type": "embedded",
        "title": "Algebra 1 — Quadratic formula: x² - 4x + 3 = 0",
        "course": "Algebra 1",
        "topic": "Quadratics",
        "source_pdf": "Algebra 1.quizzes.pdf",
        "page_number": 12,
        "question_text": "Solve x² - 4x + 3 = 0 using the quadratic formula.",
        "normalized_question": "Solve x² - 4x + 3 = 0 using the quadratic formula.",
        "problem_type": "quadratic",
        "parameters": {"a": 1, "b": -4, "c": 3, "roots": [1, 3]},
        "answer": "x = 1 and x = 3",
        "alternate_answer": None,
        "solution_text": "x = (-b +/- sqrt(b² - 4ac)) / (2a) = (4 +/- sqrt(16 - 12)) / 2 = (4 +/- 2) / 2. So x = 1 and x = 3.",
        "real_life_text": "The quadratic formula works for any quadratic equation. It is like a universal key for parabolas.",
        "real_life_text_tr": "Ikinci derece denklem formulu, herhangi bir ikinci derece denklem icin calisir. Paraboller icin evrensel bir anahtar gibidir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_alg1_zero_product_001",
        "source_type": "embedded",
        "title": "Algebra 1 — Zero Product: (x - 3)(x + 2) = 0",
        "course": "Algebra 1",
        "topic": "Factoring",
        "source_pdf": "Algebra 1.quizzes.pdf",
        "page_number": 11,
        "question_text": "Solve (x - 3)(x + 2) = 0.",
        "normalized_question": "Solve (x - 3)(x + 2) = 0.",
        "problem_type": "zero_product",
        "parameters": {"factors": ["x - 3", "x + 2"], "roots": [3, -2]},
        "answer": "x = 3 and x = -2",
        "alternate_answer": None,
        "solution_text": "If ab = 0, then a = 0 or b = 0. So x - 3 = 0 gives x = 3, and x + 2 = 0 gives x = -2.",
        "real_life_text": "The Zero Product Property says if the product of two things is zero, at least one of them must be zero.",
        "real_life_text_tr": "Sifir Carpim Ozelligi, iki seyin carpimi sifirsa, en az biri sifir olmali der.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
    {
        "id": "embedded_alg1_difference_squares_001",
        "source_type": "embedded",
        "title": "Algebra 1 — Factor x² - 9",
        "course": "Algebra 1",
        "topic": "Factoring",
        "source_pdf": "Algebra 1.quizzes.pdf",
        "page_number": 11,
        "question_text": "Factor x² - 9.",
        "normalized_question": "Factor x² - 9.",
        "problem_type": "difference_of_squares",
        "parameters": {"a": 1, "b": 3, "result": "(x + 3)(x - 3)"},
        "answer": "(x + 3)(x - 3)",
        "alternate_answer": None,
        "solution_text": "x² - 9 = x² - 3² = (x + 3)(x - 3). The difference of squares factors into a sum times a difference.",
        "real_life_text": "The difference of squares is like two perfect squares being subtracted. It always factors into a sum and a difference.",
        "real_life_text_tr": "Kareler farki, iki tam karenin cikarilmasi gibidir. Her zaman bir toplam ve bir farkin carpimina ayrilir.",
        "graph_png_path": None,
        "animation_path": None,
        "confidence": 1.0,
        "status": "ready",
        "verified": True,
    },
]

EMBEDDED_COUNT = len(EMBEDDED_COURSE_SIMULATIONS)


# ===========================================================================
# QA finalizer (Claude QA pass, 2026-06-20)
# Derives visual_type / graph_required / source_verified for every embedded
# record WITHOUT rewriting the hand-authored literals above. This keeps a
# single, auditable rule for which records are graphable vs concept cards,
# and which source citations were text-verified against the PDF page.
# Pure-Python: no import of visual_math_lab (avoids any circular import).
# ===========================================================================
GRAPHABLE_TYPES = {
    "slope_intercept", "point_slope", "two_point_line", "parallel_line",
    "perpendicular_line", "quadratic", "system_of_equations", "trig_triangle",
    "unit_circle", "trig_wave", "derivative", "integral", "vector_basic", "vector",
}

_VISUAL_TYPE_MAP = {
    "slope_intercept": "line_graph",
    "point_slope": "line_graph",
    "two_point_line": "line_graph",
    "parallel_line": "line_graph",
    "perpendicular_line": "line_graph",
    "quadratic": "parabola",
    "system_of_equations": "system_graph",
    "trig_triangle": "triangle",
    "unit_circle": "unit_circle",
    "trig_wave": "wave",
    "derivative": "derivative_graph",
    "integral": "area_graph",
    "vector_basic": "vector_graph",
    "vector": "vector_graph",
}

# Declared graphable but the text parser cannot detect it (e.g. an algebraic
# "Solve ... = 0" task). Kept as a ready, verified worked example, but not
# flagged graph_required so the loader never tries (and fails) to draw it.
_CONCEPT_OVERRIDE_IDS = {
    "embedded_alg1_quadratic_formula_001",
}

# Cited PDF page could not be text-verified (cover/image page, or imprecise
# page number inside a large aggregated PDF). The math is correct; only the
# page citation is unverified -> source_verified=False + review_reason.
_SOURCE_REVIEW = {
    "embedded_alg2_exponent_negative_base_001": "Source page text not verifiable (cited page has no extractable text)",
    "embedded_prealgebra_number_sets_natural_001": "Source page text not verifiable (cited page has no extractable text)",
    "embedded_prealgebra_number_sets_whole_001": "Source page text not verifiable (cited page has no extractable text)",
    "embedded_prealgebra_percent_decimal_001": "Source page topic keywords not found on cited page",
    "embedded_alg1_variables_001": "Source page text not verifiable (cited page has no extractable text)",
    "embedded_alg1_coefficients_001": "Source page text not verifiable (cited page has no extractable text)",
}


def _finalize_embedded_simulations(records):
    """Fill QA-derived fields in place. Idempotent; respects explicit values."""
    for r in records:
        ptype = r.get("problem_type", "")
        graphable = ptype in GRAPHABLE_TYPES and r.get("id") not in _CONCEPT_OVERRIDE_IDS
        if not r.get("visual_type"):
            r["visual_type"] = _VISUAL_TYPE_MAP.get(ptype, "concept_card") if graphable else "concept_card"
        if "graph_required" not in r:
            r["graph_required"] = bool(graphable)
        if r.get("id") in _SOURCE_REVIEW:
            r["source_verified"] = False
            r.setdefault("review_reason", _SOURCE_REVIEW[r["id"]])
        else:
            r.setdefault("source_verified", True)
        # Normalize a 'topic' key for records that only carry 'section'.
        if not r.get("topic"):
            r["topic"] = r.get("section", "") or r.get("course", "")
    return records


_finalize_embedded_simulations(EMBEDDED_COURSE_SIMULATIONS)

GRAPHABLE_COUNT = sum(1 for r in EMBEDDED_COURSE_SIMULATIONS if r.get("graph_required"))
CONCEPT_COUNT = EMBEDDED_COUNT - GRAPHABLE_COUNT
