# -*- coding: utf-8 -*-
"""
Embedded Formula Library — Pre-Algebra, Algebra 1, Geometry, Linear Algebra, Algebra 2
Pre-extracted formula and concept cards for Visual Math Lab.
"""

from pathlib import Path

EMBEDDED_FORMULA_LIBRARY = [
    # =====================================================================
    # A. Pre-Algebra  (10+)
    # =====================================================================
    {
        "id": "prea_number_sets_natural",
        "source_type": "formula",
        "course": "Pre-Algebra",
        "topic": "Number sets",
        "title": "Natural numbers",
        "formula_latex": "\\mathbb{N} = \\{1, 2, 3, 4, \\ldots\\}",
        "formula_plain": "N = {1, 2, 3, 4, ...}",
        "description": "The counting numbers. They are the positive whole numbers used for counting.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Which of the following is another name for the counting numbers?",
        "source_pdf": "Pre-Algebra.formulas.pdf",
        "page_number": 1,
        "status": "ready",
    },
    {
        "id": "prea_number_sets_whole",
        "source_type": "formula",
        "course": "Pre-Algebra",
        "topic": "Number sets",
        "title": "Whole numbers",
        "formula_latex": "\\mathbb{W} = \\{0, 1, 2, 3, \\ldots\\}",
        "formula_plain": "W = {0, 1, 2, 3, ...}",
        "description": "Natural numbers plus zero. Every natural number is a whole number, but zero is not natural.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Which set could represent whole numbers?",
        "source_pdf": "Pre-Algebra.formulas.pdf",
        "page_number": 1,
        "status": "ready",
    },
    {
        "id": "prea_number_sets_integers",
        "source_type": "formula",
        "course": "Pre-Algebra",
        "topic": "Number sets",
        "title": "Integers",
        "formula_latex": "\\mathbb{Z} = \\{\\ldots, -3, -2, -1, 0, 1, 2, 3, \\ldots\\}",
        "formula_plain": "Z = {..., -3, -2, -1, 0, 1, 2, 3, ...}",
        "description": "Whole numbers and their negatives. Includes zero, positive and negative counting numbers.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Which set includes both positive and negative whole numbers plus zero?",
        "source_pdf": "Pre-Algebra.formulas.pdf",
        "page_number": 1,
        "status": "ready",
    },
    {
        "id": "prea_number_sets_rational",
        "source_type": "formula",
        "course": "Pre-Algebra",
        "topic": "Number sets",
        "title": "Rational numbers",
        "formula_latex": "\\mathbb{Q} = \\left\\{ \\frac{a}{b} \\mid a, b \\in \\mathbb{Z}, b \\neq 0 \\right\\}",
        "formula_plain": "Q = {a/b | a, b are integers, b != 0}",
        "description": "Any number that can be written as a fraction of two integers where the denominator is not zero.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Is 0.75 a rational number?",
        "source_pdf": "Pre-Algebra.formulas.pdf",
        "page_number": 2,
        "status": "ready",
    },
    {
        "id": "prea_number_sets_irrational",
        "source_type": "formula",
        "course": "Pre-Algebra",
        "topic": "Number sets",
        "title": "Irrational numbers",
        "formula_latex": "\\{ x \\mid x \\text{ cannot be written as } a/b \\text{ for integers } a, b \\}",
        "formula_plain": "Numbers that cannot be written as a fraction of two integers",
        "description": "Numbers whose decimal expansions go on forever without repeating. Examples include sqrt(2) and pi.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Is the square root of 2 a rational or irrational number?",
        "source_pdf": "Pre-Algebra.formulas.pdf",
        "page_number": 2,
        "status": "ready",
    },
    {
        "id": "prea_number_sets_real",
        "source_type": "formula",
        "course": "Pre-Algebra",
        "topic": "Number sets",
        "title": "Real numbers",
        "formula_latex": "\\mathbb{R} = \\mathbb{Q} \\cup \\text{irrational numbers}",
        "formula_plain": "R = Q union irrational numbers = all rational and irrational numbers together",
        "description": "All rational and irrational numbers combined. Every point on the number line is a real number.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "What is the most inclusive number set that includes both 1/2 and sqrt(2)?",
        "source_pdf": "Pre-Algebra.formulas.pdf",
        "page_number": 2,
        "status": "ready",
    },
    {
        "id": "prea_set_notation_element",
        "source_type": "formula",
        "course": "Pre-Algebra",
        "topic": "Set notation",
        "title": "Element of",
        "formula_latex": "a \\in S",
        "formula_plain": "a is an element of S",
        "description": "The symbol 'in' means that a is a member of the set S.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Is 3 an element of the set {1, 2, 3}?",
        "source_pdf": "Pre-Algebra.formulas.pdf",
        "page_number": 3,
        "status": "ready",
    },
    {
        "id": "prea_set_notation_subset",
        "source_type": "formula",
        "course": "Pre-Algebra",
        "topic": "Set notation",
        "title": "Subset",
        "formula_latex": "A \\subseteq B",
        "formula_plain": "A is a subset of B",
        "description": "Every element of A is also an element of B. If A = B, it is still a subset.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Is {1, 2} a subset of {1, 2, 3}?",
        "source_pdf": "Pre-Algebra.formulas.pdf",
        "page_number": 3,
        "status": "ready",
    },
    {
        "id": "prea_set_notation_union",
        "source_type": "formula",
        "course": "Pre-Algebra",
        "topic": "Set notation",
        "title": "Union",
        "formula_latex": "A \\cup B = \\{ x \\mid x \\in A \\text{ or } x \\in B \\}",
        "formula_plain": "A union B = all elements that are in A or in B (or both)",
        "description": "The union of two sets contains all elements that are in at least one of the sets.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "What is the union of {1, 2} and {2, 3}?",
        "source_pdf": "Pre-Algebra.formulas.pdf",
        "page_number": 3,
        "status": "ready",
    },
    {
        "id": "prea_set_notation_intersection",
        "source_type": "formula",
        "course": "Pre-Algebra",
        "topic": "Set notation",
        "title": "Intersection",
        "formula_latex": "A \\cap B = \\{ x \\mid x \\in A \\text{ and } x \\in B \\}",
        "formula_plain": "A intersect B = all elements that are in both A and B",
        "description": "The intersection of two sets contains only the elements that are common to both sets.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "What is the intersection of {1, 2, 3} and {2, 3, 4}?",
        "source_pdf": "Pre-Algebra.formulas.pdf",
        "page_number": 3,
        "status": "ready",
    },
    {
        "id": "prea_identity_additive",
        "source_type": "formula",
        "course": "Pre-Algebra",
        "topic": "Identity numbers",
        "title": "Additive identity",
        "formula_latex": "a + 0 = a",
        "formula_plain": "a + 0 = a",
        "description": "Adding zero to any number leaves it unchanged. Zero is the additive identity.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "What is the additive identity?",
        "source_pdf": "Pre-Algebra.formulas.pdf",
        "page_number": 4,
        "status": "ready",
    },
    {
        "id": "prea_identity_multiplicative",
        "source_type": "formula",
        "course": "Pre-Algebra",
        "topic": "Identity numbers",
        "title": "Multiplicative identity",
        "formula_latex": "a \\cdot 1 = a",
        "formula_plain": "a * 1 = a",
        "description": "Multiplying any number by one leaves it unchanged. One is the multiplicative identity.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "What is the multiplicative identity?",
        "source_pdf": "Pre-Algebra.formulas.pdf",
        "page_number": 4,
        "status": "ready",
    },
    {
        "id": "prea_pemdas",
        "source_type": "formula",
        "course": "Pre-Algebra",
        "topic": "Order of operations",
        "title": "PEMDAS",
        "formula_latex": "\\text{Parentheses} \\rightarrow \\text{Exponents} \\rightarrow \\text{Multiplication/Division} \\rightarrow \\text{Addition/Subtraction}",
        "formula_plain": "PEMDAS: Parentheses, Exponents, Multiplication/Division, Addition/Subtraction",
        "description": "The standard order in which operations should be performed in an arithmetic expression.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Evaluate 3 + 4 * 2",
        "source_pdf": "Pre-Algebra.formulas.pdf",
        "page_number": 5,
        "status": "ready",
    },
    {
        "id": "prea_absolute_value",
        "source_type": "formula",
        "course": "Pre-Algebra",
        "topic": "Absolute value",
        "title": "Absolute value",
        "formula_latex": "|a| = \\begin{cases} a & \\text{if } a \\geq 0 \\\\ -a & \\text{if } a < 0 \\end{cases}",
        "formula_plain": "|a| = a if a >= 0, else -a",
        "description": "The distance of a number from zero on the number line, always non-negative.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "What is the absolute value of -7?",
        "source_pdf": "Pre-Algebra.formulas.pdf",
        "page_number": 5,
        "status": "ready",
    },
    {
        "id": "prea_fraction_addition",
        "source_type": "formula",
        "course": "Pre-Algebra",
        "topic": "Fractions",
        "title": "Adding fractions",
        "formula_latex": "\\frac{a}{b} + \\frac{c}{d} = \\frac{ad + bc}{bd}",
        "formula_plain": "a/b + c/d = (ad + bc) / (bd)",
        "description": "Find a common denominator by multiplying the two denominators, then add the numerators.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Add 1/2 + 1/3",
        "source_pdf": "Pre-Algebra.formulas.pdf",
        "page_number": 6,
        "status": "ready",
    },
    {
        "id": "prea_fraction_multiply",
        "source_type": "formula",
        "course": "Pre-Algebra",
        "topic": "Fractions",
        "title": "Multiplying fractions",
        "formula_latex": "\\frac{a}{b} \\cdot \\frac{c}{d} = \\frac{ac}{bd}",
        "formula_plain": "a/b * c/d = (ac) / (bd)",
        "description": "Multiply the numerators together and the denominators together.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Multiply 2/3 * 3/5",
        "source_pdf": "Pre-Algebra.formulas.pdf",
        "page_number": 6,
        "status": "ready",
    },
    # =====================================================================
    # B. Algebra 1  (15+)
    # =====================================================================
    {
        "id": "alg1_variable_definition",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Variables, constants, coefficients",
        "title": "Variable",
        "formula_latex": "x, y, z, \\ldots",
        "formula_plain": "x, y, z, ...",
        "description": "A symbol (usually a letter) that represents an unknown quantity or a quantity that can change.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "In the expression 3x + 2, what is the variable?",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 1,
        "status": "ready",
    },
    {
        "id": "alg1_constant_definition",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Variables, constants, coefficients",
        "title": "Constant",
        "formula_latex": "c \\text{ (fixed value)}",
        "formula_plain": "c (fixed value)",
        "description": "A fixed number whose value does not change in a given expression or equation.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "In the expression 3x + 2, what is the constant?",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 1,
        "status": "ready",
    },
    {
        "id": "alg1_coefficient_definition",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Variables, constants, coefficients",
        "title": "Coefficient",
        "formula_latex": "3x \\rightarrow \\text{coefficient } 3",
        "formula_plain": "3x -> coefficient is 3",
        "description": "The numerical factor multiplied by a variable in a term. In 3x, the coefficient is 3.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "What is the coefficient of x in the term -5x?",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 1,
        "status": "ready",
    },
    {
        "id": "alg1_expression_definition",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Expressions and equations",
        "title": "Expression",
        "formula_latex": "3x + 2y - 7",
        "formula_plain": "3x + 2y - 7",
        "description": "A mathematical phrase that can contain numbers, variables, and operation symbols, but no equals sign.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Is 2x + 5 an expression or an equation?",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 2,
        "status": "ready",
    },
    {
        "id": "alg1_equation_definition",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Expressions and equations",
        "title": "Equation",
        "formula_latex": "3x + 2 = 11",
        "formula_plain": "3x + 2 = 11",
        "description": "A mathematical statement that two expressions are equal, containing an equals sign.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Is 2x + 5 = 9 an equation?",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 2,
        "status": "ready",
    },
    {
        "id": "alg1_associative_property",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Properties",
        "title": "Associative Property",
        "formula_latex": "(a + b) + c = a + (b + c) \\quad ; \\quad (a \\cdot b) \\cdot c = a \\cdot (b \\cdot c)",
        "formula_plain": "(a + b) + c = a + (b + c) ; (a * b) * c = a * (b * c)",
        "description": "Grouping of addends or factors does not change the sum or product.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Show that (2 + 3) + 4 = 2 + (3 + 4)",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 3,
        "status": "ready",
    },
    {
        "id": "alg1_commutative_property",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Properties",
        "title": "Commutative Property",
        "formula_latex": "a + b = b + a \\quad ; \\quad a \\cdot b = b \\cdot a",
        "formula_plain": "a + b = b + a ; a * b = b * a",
        "description": "The order of addends or factors does not change the sum or product.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Show that 3 + 5 = 5 + 3",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 3,
        "status": "ready",
    },
    {
        "id": "alg1_distributive_property",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Properties",
        "title": "Distributive Property",
        "formula_latex": "a(b + c) = ab + ac",
        "formula_plain": "a(b + c) = ab + ac",
        "description": "Multiply a single term across a sum or difference inside parentheses.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Expand 3(x + 4)",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 3,
        "status": "ready",
    },
    {
        "id": "alg1_transitive_property",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Properties",
        "title": "Transitive Property",
        "formula_latex": "\\text{If } a = b \\text{ and } b = c, \\text{ then } a = c",
        "formula_plain": "If a = b and b = c, then a = c",
        "description": "If two quantities are each equal to a third quantity, then they are equal to each other.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "If x = 5 and 5 = y, what is x in terms of y?",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 3,
        "status": "ready",
    },
    {
        "id": "alg1_linear_equation",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Linear equations",
        "title": "Standard form of a linear equation",
        "formula_latex": "Ax + By = C",
        "formula_plain": "Ax + By = C",
        "description": "A linear equation in two variables written in standard form. A, B, and C are constants.",
        "visual_type": "line",
        "supported_by_visual_math": True,
        "example_question": "Rewrite y = 2x + 1 in standard form",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 4,
        "status": "ready",
    },
    {
        "id": "alg1_slope_formula",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Slope",
        "title": "Slope formula",
        "formula_latex": "m = \\frac{y_2 - y_1}{x_2 - x_1}",
        "formula_plain": "m = (y2 - y1) / (x2 - x1)",
        "description": "The slope of a line is the ratio of the vertical change (rise) to the horizontal change (run) between two points.",
        "visual_type": "line",
        "supported_by_visual_math": True,
        "example_question": "Find the slope between (1, 2) and (5, 4)",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 5,
        "status": "ready",
    },
    {
        "id": "alg1_point_slope_form",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Point-slope form",
        "title": "Point-slope form",
        "formula_latex": "y - y_1 = m(x - x_1)",
        "formula_plain": "y - y1 = m(x - x1)",
        "description": "Used to write the equation of a line when a slope and a point are known.",
        "visual_type": "line",
        "supported_by_visual_math": True,
        "example_question": "Write the equation of the line in point-slope form with m = -1/4 and point = (-6, 1)",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 6,
        "status": "ready",
    },
    {
        "id": "alg1_slope_intercept_form",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Slope-intercept form",
        "title": "Slope-intercept form",
        "formula_latex": "y = mx + b",
        "formula_plain": "y = mx + b",
        "description": "The most common form of a linear equation. m is the slope and b is the y-intercept.",
        "visual_type": "line",
        "supported_by_visual_math": True,
        "example_question": "Find the equation of a line with slope 1/2 and y-intercept -2",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 6,
        "status": "ready",
    },
    {
        "id": "alg1_function_notation",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Function notation",
        "title": "Function notation",
        "formula_latex": "f(x) = mx + b",
        "formula_plain": "f(x) = mx + b",
        "description": "f(x) is read as 'f of x' and represents the output value of the function f for the input x.",
        "visual_type": "function",
        "supported_by_visual_math": True,
        "example_question": "Evaluate f(3) if f(x) = 2x + 1",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 7,
        "status": "ready",
    },
    {
        "id": "alg1_domain_range",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Domain and range",
        "title": "Domain and range",
        "formula_latex": "\\text{Domain} = \\{x \\mid x \\text{ is defined}\\} \\quad ; \\quad \\text{Range} = \\{f(x) \\mid x \\in \\text{Domain}\\}",
        "formula_plain": "Domain = set of all valid inputs; Range = set of all possible outputs",
        "description": "Domain is the set of all possible input values. Range is the set of all possible output values.",
        "visual_type": "function",
        "supported_by_visual_math": True,
        "example_question": "What is the domain of f(x) = 1/x?",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 8,
        "status": "ready",
    },
    {
        "id": "alg1_system_substitution",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Systems of equations",
        "title": "Substitution method",
        "formula_latex": "\\text{Solve one equation for a variable, then substitute into the other equation.}",
        "formula_plain": "Solve one equation for a variable, then substitute into the other equation",
        "description": "A method for solving a system of equations by isolating one variable and substituting it into the other equation.",
        "visual_type": "system",
        "supported_by_visual_math": True,
        "example_question": "Solve y = x + 7 and x + 2y = -16 by substitution",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 9,
        "status": "ready",
    },
    {
        "id": "alg1_system_elimination",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Systems of equations",
        "title": "Elimination method",
        "formula_latex": "\\text{Add or subtract equations to eliminate one variable.}",
        "formula_plain": "Add or subtract equations to eliminate one variable",
        "description": "A method for solving a system by adding or subtracting equations so that one variable cancels out.",
        "visual_type": "system",
        "supported_by_visual_math": True,
        "example_question": "Solve x - 3y = -7 and 2x - 3y = 4 by elimination",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 9,
        "status": "ready",
    },
    {
        "id": "alg1_polynomial_degree",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Polynomials",
        "title": "Degree of a polynomial",
        "formula_latex": "\\deg(3x^2 + 2x - 1) = 2",
        "formula_plain": "deg(3x^2 + 2x - 1) = 2",
        "description": "The highest exponent of the variable in any term of the polynomial.",
        "visual_type": "polynomial",
        "supported_by_visual_math": False,
        "example_question": "What is the degree of 4x^3 + 2x^2 - x + 7?",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 10,
        "status": "ready",
    },
    {
        "id": "alg1_factoring_difference_squares",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Factoring",
        "title": "Difference of squares",
        "formula_latex": "a^2 - b^2 = (a + b)(a - b)",
        "formula_plain": "a^2 - b^2 = (a + b)(a - b)",
        "description": "The difference of two perfect squares can always be factored into the product of a sum and a difference.",
        "visual_type": "polynomial",
        "supported_by_visual_math": False,
        "example_question": "Factor x^2 - 9",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 11,
        "status": "ready",
    },
    {
        "id": "alg1_quadratic_formula",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Quadratics",
        "title": "Quadratic formula",
        "formula_latex": "x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}",
        "formula_plain": "x = (-b +/- sqrt(b^2 - 4ac)) / (2a)",
        "description": "Gives the solutions to any quadratic equation ax^2 + bx + c = 0. The discriminant b^2 - 4ac determines the number of real roots.",
        "visual_type": "quadratic",
        "supported_by_visual_math": True,
        "example_question": "Solve x^2 - 4x + 3 = 0 using the quadratic formula",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 12,
        "status": "ready",
    },
    # =====================================================================
    # C. Geometry  (20+)
    # =====================================================================
    {
        "id": "geo_points_lines_rays",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Points, lines, rays, planes",
        "title": "Point, line, ray, plane",
        "formula_latex": "\\text{Point } P \\quad ; \\quad \\text{Line } \\overleftrightarrow{AB} \\quad ; \\quad \\text{Ray } \\overrightarrow{AB} \\quad ; \\quad \\text{Plane } \\Pi",
        "formula_plain": "Point P ; Line AB ; Ray AB ; Plane Pi",
        "description": "A point has no dimension. A line extends infinitely in both directions. A ray extends infinitely in one direction. A plane is a flat, two-dimensional surface.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "What is the difference between a line and a ray?",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 1,
        "status": "ready",
    },
    {
        "id": "geo_collinear_coplanar",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Collinear and coplanar points",
        "title": "Collinear and coplanar",
        "formula_latex": "\\text{Collinear: points on the same line} \\quad ; \\quad \\text{Coplanar: points in the same plane}",
        "formula_plain": "Collinear: points on the same line; Coplanar: points in the same plane",
        "description": "Collinear points lie on a single straight line. Coplanar points lie in a single flat plane.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Are three points always coplanar?",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 1,
        "status": "ready",
    },
    {
        "id": "geo_segment_addition",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Segment addition postulate",
        "title": "Segment Addition Postulate",
        "formula_latex": "AC = AB + BC",
        "formula_plain": "AC = AB + BC",
        "description": "If point B lies between points A and C on a line segment, then the whole segment AC equals the sum of the parts AB and BC.",
        "visual_type": "segment",
        "supported_by_visual_math": False,
        "example_question": "If AB = 5 and BC = 3, what is AC?",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 2,
        "status": "ready",
    },
    {
        "id": "geo_slope_segment",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Slope of a line segment",
        "title": "Slope of a line segment",
        "formula_latex": "m = \\frac{y_2 - y_1}{x_2 - x_1}",
        "formula_plain": "m = (y2 - y1) / (x2 - x1)",
        "description": "The slope between two points on a line segment is the ratio of vertical change to horizontal change.",
        "visual_type": "line",
        "supported_by_visual_math": True,
        "example_question": "Find the slope between (1, 2) and (5, 4)",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 3,
        "status": "ready",
    },
    {
        "id": "geo_distance_2d",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Distance formula",
        "title": "Distance formula (2D)",
        "formula_latex": "d = \\sqrt{(x_1 - x_2)^2 + (y_1 - y_2)^2}",
        "formula_plain": "d = sqrt((x1 - x2)^2 + (y1 - y2)^2)",
        "description": "The distance between two points in a plane is the square root of the sum of the squared differences of their coordinates.",
        "visual_type": "geometry_distance",
        "supported_by_visual_math": True,
        "example_question": "Find the distance between (1, 2) and (4, 6)",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 4,
        "status": "ready",
    },
    {
        "id": "geo_midpoint_2d",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Midpoint formula",
        "title": "Midpoint formula (2D)",
        "formula_latex": "M = \\left( \\frac{x_1 + x_2}{2}, \\frac{y_1 + y_2}{2} \\right)",
        "formula_plain": "M = ((x1 + x2)/2, (y1 + y2)/2)",
        "description": "The midpoint of a line segment is the average of the coordinates of its endpoints.",
        "visual_type": "geometry_midpoint",
        "supported_by_visual_math": True,
        "example_question": "Find the midpoint between (2, 4) and (6, 8)",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 4,
        "status": "ready",
    },
    {
        "id": "geo_distance_3d",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Distance formula",
        "title": "Distance formula (3D)",
        "formula_latex": "d = \\sqrt{(x_1 - x_2)^2 + (y_1 - y_2)^2 + (z_1 - z_2)^2}",
        "formula_plain": "d = sqrt((x1 - x2)^2 + (y1 - y2)^2 + (z1 - z2)^2)",
        "description": "The distance between two points in three-dimensional space extends the 2D formula with a z-coordinate term.",
        "visual_type": "geometry_distance",
        "supported_by_visual_math": True,
        "example_question": "Find the distance between (1, 2, 3) and (4, 6, 8)",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 5,
        "status": "ready",
    },
    {
        "id": "geo_midpoint_3d",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Midpoint formula",
        "title": "Midpoint formula (3D)",
        "formula_latex": "M = \\left( \\frac{x_1 + x_2}{2}, \\frac{y_1 + y_2}{2}, \\frac{z_1 + z_2}{2} \\right)",
        "formula_plain": "M = ((x1 + x2)/2, (y1 + y2)/2, (z1 + z2)/2)",
        "description": "The midpoint in 3D averages all three coordinates of the endpoints.",
        "visual_type": "geometry_midpoint",
        "supported_by_visual_math": True,
        "example_question": "Find the midpoint between (2, 4, 6) and (8, 10, 12)",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 5,
        "status": "ready",
    },
    {
        "id": "geo_parallel_slopes",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Parallel line segments",
        "title": "Parallel line segments",
        "formula_latex": "m_1 = m_2",
        "formula_plain": "m1 = m2",
        "description": "Two line segments are parallel if and only if their slopes are equal.",
        "visual_type": "line",
        "supported_by_visual_math": True,
        "example_question": "Are the lines y = 2x + 1 and y = 2x - 3 parallel?",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 6,
        "status": "ready",
    },
    {
        "id": "geo_perpendicular_slopes",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Perpendicular line segments",
        "title": "Perpendicular line segments",
        "formula_latex": "m_1 \\cdot m_2 = -1 \\quad \\text{or} \\quad m_2 = -\\frac{1}{m_1}",
        "formula_plain": "m1 * m2 = -1  or  m2 = -1/m1",
        "description": "Two line segments are perpendicular if and only if the product of their slopes is -1. The slope of one is the negative reciprocal of the other.",
        "visual_type": "line",
        "supported_by_visual_math": True,
        "example_question": "Are the lines y = 2x + 1 and y = -1/2x + 3 perpendicular?",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 6,
        "status": "ready",
    },
    {
        "id": "geo_angle_360",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Angle measures",
        "title": "Full angle",
        "formula_latex": "360^\\circ",
        "formula_plain": "360 degrees",
        "description": "A full rotation around a point measures 360 degrees.",
        "visual_type": "angle",
        "supported_by_visual_math": False,
        "example_question": "How many degrees are in a full circle?",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 7,
        "status": "ready",
    },
    {
        "id": "geo_angle_180",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Angle measures",
        "title": "Straight angle",
        "formula_latex": "180^\\circ",
        "formula_plain": "180 degrees",
        "description": "A straight line forms a straight angle of 180 degrees.",
        "visual_type": "angle",
        "supported_by_visual_math": False,
        "example_question": "How many degrees are in a straight angle?",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 7,
        "status": "ready",
    },
    {
        "id": "geo_angle_90",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Angle measures",
        "title": "Right angle",
        "formula_latex": "90^\\circ",
        "formula_plain": "90 degrees",
        "description": "A right angle measures exactly 90 degrees. It is formed by two perpendicular lines.",
        "visual_type": "angle",
        "supported_by_visual_math": False,
        "example_question": "How many degrees are in a right angle?",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 7,
        "status": "ready",
    },
    {
        "id": "geo_complementary",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Complementary angles",
        "title": "Complementary angles",
        "formula_latex": "a + b = 90^\\circ",
        "formula_plain": "a + b = 90 degrees",
        "description": "Two angles are complementary if their measures add up to 90 degrees.",
        "visual_type": "angle",
        "supported_by_visual_math": False,
        "example_question": "If one angle is 35 degrees, what is its complement?",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 8,
        "status": "ready",
    },
    {
        "id": "geo_supplementary",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Supplementary angles",
        "title": "Supplementary angles",
        "formula_latex": "a + b = 180^\\circ",
        "formula_plain": "a + b = 180 degrees",
        "description": "Two angles are supplementary if their measures add up to 180 degrees.",
        "visual_type": "angle",
        "supported_by_visual_math": False,
        "example_question": "If one angle is 110 degrees, what is its supplement?",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 8,
        "status": "ready",
    },
    {
        "id": "geo_vertical_angles",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Vertical angles",
        "title": "Vertical angles",
        "formula_latex": "\\angle 1 = \\angle 2",
        "formula_plain": "angle 1 = angle 2",
        "description": "When two lines intersect, the opposite (vertical) angles are always equal in measure.",
        "visual_type": "angle",
        "supported_by_visual_math": False,
        "example_question": "If two intersecting lines form angles of 40 and 140 degrees, what are the other two angles?",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 8,
        "status": "ready",
    },
    {
        "id": "geo_angle_bisector",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Angle bisectors",
        "title": "Angle bisector",
        "formula_latex": "\\text{If } \\overrightarrow{BD} \\text{ bisects } \\angle ABC, \\text{ then } \\angle ABD = \\angle DBC",
        "formula_plain": "If BD bisects angle ABC, then angle ABD = angle DBC",
        "description": "An angle bisector divides an angle into two equal smaller angles.",
        "visual_type": "angle",
        "supported_by_visual_math": False,
        "example_question": "If angle ABC is 80 degrees and BD bisects it, what is angle ABD?",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 9,
        "status": "ready",
    },
    {
        "id": "geo_perpendicular_bisector",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Perpendicular bisectors",
        "title": "Perpendicular bisector",
        "formula_latex": "\\text{Line through midpoint of } \\overline{AB} \\text{ at } 90^\\circ",
        "formula_plain": "Line through midpoint of AB at 90 degrees",
        "description": "A line that passes through the midpoint of a segment and is perpendicular to it. Every point on it is equidistant from the segment's endpoints.",
        "visual_type": "segment",
        "supported_by_visual_math": False,
        "example_question": "What is the perpendicular bisector of the segment from (0, 0) to (4, 0)?",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 9,
        "status": "ready",
    },
    {
        "id": "geo_transversal_corresponding",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Transversals",
        "title": "Corresponding angles",
        "formula_latex": "\\text{Corresponding angles are equal when lines are parallel}",
        "formula_plain": "Corresponding angles are equal when lines are parallel",
        "description": "When a transversal crosses two parallel lines, corresponding angles occupy the same relative position and are equal.",
        "visual_type": "angle",
        "supported_by_visual_math": False,
        "example_question": "If two parallel lines are cut by a transversal and one corresponding angle is 70 degrees, what is the other?",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 10,
        "status": "ready",
    },
    {
        "id": "geo_triangle_sum",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Triangles",
        "title": "Triangle angle sum",
        "formula_latex": "\\angle A + \\angle B + \\angle C = 180^\\circ",
        "formula_plain": "angle A + angle B + angle C = 180 degrees",
        "description": "The three interior angles of any triangle always add up to 180 degrees.",
        "visual_type": "angle",
        "supported_by_visual_math": False,
        "example_question": "If a triangle has angles 50 and 60 degrees, what is the third angle?",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 11,
        "status": "ready",
    },
    {
        "id": "geo_pythagorean",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Triangles",
        "title": "Pythagorean Theorem",
        "formula_latex": "a^2 + b^2 = c^2",
        "formula_plain": "a^2 + b^2 = c^2",
        "description": "In a right triangle, the square of the hypotenuse equals the sum of the squares of the two legs.",
        "visual_type": "concept_card",
        "supported_by_visual_math": True,
        "example_question": "If a = 3 and b = 4, what is c?",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 12,
        "status": "ready",
    },
    {
        "id": "geo_triangle_area",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Triangles",
        "title": "Area of a triangle",
        "formula_latex": "A = \\frac{1}{2} bh",
        "formula_plain": "A = 1/2 * b * h",
        "description": "The area of a triangle is half the product of its base and corresponding height.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Find the area of a triangle with base 6 and height 4",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 13,
        "status": "ready",
    },
    {
        "id": "geo_circle_area",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Circles",
        "title": "Area of a circle",
        "formula_latex": "A = \\pi r^2",
        "formula_plain": "A = pi * r^2",
        "description": "The area of a circle is pi times the square of its radius.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Find the area of a circle with radius 3",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 14,
        "status": "ready",
    },
    {
        "id": "geo_circumference",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Circles",
        "title": "Circumference of a circle",
        "formula_latex": "C = 2\\pi r",
        "formula_plain": "C = 2 * pi * r",
        "description": "The circumference of a circle is 2 pi times its radius.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Find the circumference of a circle with radius 5",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 14,
        "status": "ready",
    },
    # =====================================================================
    # D. Linear Algebra  (10+)
    # =====================================================================
    {
        "id": "linalg_system_substitution",
        "source_type": "formula",
        "course": "Linear Algebra",
        "topic": "Solving systems with substitution",
        "title": "Substitution method",
        "formula_latex": "\\text{Solve one equation for a variable, then substitute into the other.}",
        "formula_plain": "Solve one equation for a variable, then substitute into the other",
        "description": "A systematic way to solve a system of linear equations by expressing one variable in terms of another.",
        "visual_type": "system",
        "supported_by_visual_math": True,
        "example_question": "Solve y = x + 7 and x + 2y = -16 by substitution",
        "source_pdf": "Linear Algebra.formulas.pdf",
        "page_number": 1,
        "status": "ready",
    },
    {
        "id": "linalg_system_elimination",
        "source_type": "formula",
        "course": "Linear Algebra",
        "topic": "Solving systems with elimination",
        "title": "Elimination method",
        "formula_latex": "\\text{Add or subtract equations to eliminate one variable.}",
        "formula_plain": "Add or subtract equations to eliminate one variable",
        "description": "A method for solving linear systems by eliminating one variable through addition or subtraction of equations.",
        "visual_type": "system",
        "supported_by_visual_math": True,
        "example_question": "Solve x - 3y = -7 and 2x - 3y = 4 by elimination",
        "source_pdf": "Linear Algebra.formulas.pdf",
        "page_number": 2,
        "status": "ready",
    },
    {
        "id": "linalg_system_graphing",
        "source_type": "formula",
        "course": "Linear Algebra",
        "topic": "Graphing method",
        "title": "Graphing method",
        "formula_latex": "\\text{Graph both lines; the intersection is the solution.}",
        "formula_plain": "Graph both lines; the intersection is the solution",
        "description": "Solve a system by plotting both equations on the same coordinate plane and reading the intersection point.",
        "visual_type": "system",
        "supported_by_visual_math": True,
        "example_question": "Solve y = 2x + 1 and y = -x + 4 by graphing",
        "source_pdf": "Linear Algebra.formulas.pdf",
        "page_number": 3,
        "status": "ready",
    },
    {
        "id": "linalg_matrix_dimensions",
        "source_type": "formula",
        "course": "Linear Algebra",
        "topic": "Matrix dimensions",
        "title": "Matrix dimensions",
        "formula_latex": "m \\times n \\text{ matrix has } m \\text{ rows and } n \\text{ columns}",
        "formula_plain": "m x n matrix has m rows and n columns",
        "description": "The size of a matrix is given by its number of rows followed by its number of columns.",
        "visual_type": "matrix",
        "supported_by_visual_math": False,
        "example_question": "What are the dimensions of a 3x4 matrix?",
        "source_pdf": "Linear Algebra.formulas.pdf",
        "page_number": 4,
        "status": "ready",
    },
    {
        "id": "linalg_matrix_entry",
        "source_type": "formula",
        "course": "Linear Algebra",
        "topic": "Matrix entries",
        "title": "Matrix entry notation",
        "formula_latex": "a_{ij} = \\text{entry in row } i \\text{ and column } j",
        "formula_plain": "a_ij = entry in row i and column j",
        "description": "The subscript notation a_ij identifies the element located in the i-th row and j-th column of a matrix.",
        "visual_type": "matrix",
        "supported_by_visual_math": False,
        "example_question": "What is a_23 in a given matrix?",
        "source_pdf": "Linear Algebra.formulas.pdf",
        "page_number": 4,
        "status": "ready",
    },
    {
        "id": "linalg_augmented_matrix",
        "source_type": "formula",
        "course": "Linear Algebra",
        "topic": "Augmented matrix",
        "title": "Augmented matrix",
        "formula_latex": "[A | b]",
        "formula_plain": "[A | b]",
        "description": "An augmented matrix combines the coefficient matrix A and the constant vector b with a vertical bar separating them. It is used to solve systems via row operations.",
        "visual_type": "augmented_matrix",
        "supported_by_visual_math": False,
        "example_question": "Write the augmented matrix for 2x + 3y = 5 and x - y = 1",
        "source_pdf": "Linear Algebra.formulas.pdf",
        "page_number": 5,
        "status": "ready",
    },
    {
        "id": "linalg_row_operations",
        "source_type": "formula",
        "course": "Linear Algebra",
        "topic": "Row operations",
        "title": "Elementary row operations",
        "formula_latex": "1. \\text{Swap rows} \\quad 2. \\text{Multiply a row by a nonzero constant} \\quad 3. \\text{Add a multiple of one row to another}",
        "formula_plain": "1. Swap rows; 2. Multiply a row by nonzero constant; 3. Add multiple of one row to another",
        "description": "Three allowed operations that do not change the solution set of a linear system. They are used to reduce an augmented matrix to row-echelon form.",
        "visual_type": "augmented_matrix",
        "supported_by_visual_math": False,
        "example_question": "Use row operations to solve a system",
        "source_pdf": "Linear Algebra.formulas.pdf",
        "page_number": 5,
        "status": "ready",
    },
    {
        "id": "linalg_matrix_addition",
        "source_type": "formula",
        "course": "Linear Algebra",
        "topic": "Matrix addition",
        "title": "Matrix addition",
        "formula_latex": "A + B = [a_{ij} + b_{ij}]",
        "formula_plain": "A + B = [a_ij + b_ij]",
        "description": "Add two matrices of the same dimensions by adding their corresponding entries element-wise.",
        "visual_type": "matrix",
        "supported_by_visual_math": False,
        "example_question": "Add [[1, 2], [3, 4]] and [[5, 6], [7, 8]]",
        "source_pdf": "Linear Algebra.formulas.pdf",
        "page_number": 6,
        "status": "ready",
    },
    {
        "id": "linalg_scalar_multiplication",
        "source_type": "formula",
        "course": "Linear Algebra",
        "topic": "Scalar multiplication",
        "title": "Scalar multiplication",
        "formula_latex": "kA = [k \\cdot a_{ij}]",
        "formula_plain": "kA = [k * a_ij]",
        "description": "Multiply every entry of a matrix by a single scalar value k.",
        "visual_type": "matrix",
        "supported_by_visual_math": False,
        "example_question": "Multiply 3 * [[1, 2], [3, 4]]",
        "source_pdf": "Linear Algebra.formulas.pdf",
        "page_number": 6,
        "status": "ready",
    },
    {
        "id": "linalg_matrix_multiplication",
        "source_type": "formula",
        "course": "Linear Algebra",
        "topic": "Matrix multiplication",
        "title": "Matrix multiplication",
        "formula_latex": "(AB)_{ij} = \\sum_{k=1}^{n} a_{ik} b_{kj}",
        "formula_plain": "(AB)_ij = sum from k=1 to n of a_ik * b_kj",
        "description": "The entry in row i and column j of the product AB is the dot product of row i of A and column j of B. The number of columns in A must equal the number of rows in B.",
        "visual_type": "matrix",
        "supported_by_visual_math": False,
        "example_question": "Multiply a 2x3 matrix by a 3x2 matrix",
        "source_pdf": "Linear Algebra.formulas.pdf",
        "page_number": 7,
        "status": "ready",
    },
    {
        "id": "linalg_determinant_2x2",
        "source_type": "formula",
        "course": "Linear Algebra",
        "topic": "Determinants",
        "title": "Determinant of a 2x2 matrix",
        "formula_latex": "\\det \\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix} = ad - bc",
        "formula_plain": "det([[a, b], [c, d]]) = ad - bc",
        "description": "The determinant of a 2x2 matrix is the product of the main diagonal entries minus the product of the off-diagonal entries.",
        "visual_type": "matrix",
        "supported_by_visual_math": False,
        "example_question": "Find the determinant of [[2, 3], [4, 5]]",
        "source_pdf": "Linear Algebra.formulas.pdf",
        "page_number": 8,
        "status": "ready",
    },
    {
        "id": "linalg_inverse_2x2",
        "source_type": "formula",
        "course": "Linear Algebra",
        "topic": "Inverse matrices",
        "title": "Inverse of a 2x2 matrix",
        "formula_latex": "A^{-1} = \\frac{1}{ad - bc} \\begin{pmatrix} d & -b \\\\ -c & a \\end{pmatrix}",
        "formula_plain": "A^-1 = 1/(ad - bc) * [[d, -b], [-c, a]]",
        "description": "The inverse of a 2x2 matrix exists when the determinant ad - bc is not zero. It swaps the diagonal entries and negates the off-diagonal entries, then divides by the determinant.",
        "visual_type": "matrix",
        "supported_by_visual_math": False,
        "example_question": "Find the inverse of [[1, 2], [3, 4]]",
        "source_pdf": "Linear Algebra.formulas.pdf",
        "page_number": 8,
        "status": "ready",
    },
    # =====================================================================
    # E. Algebra 2  (10+)
    # =====================================================================
    {
        "id": "alg2_power_negative_base",
        "source_type": "formula",
        "course": "Algebra 2",
        "topic": "Powers of negative bases",
        "title": "Powers of negative bases",
        "formula_latex": "(-a)^n = (-1)^n a^n",
        "formula_plain": "(-a)^n = (-1)^n * a^n",
        "description": "A negative base raised to an even power gives a positive result; to an odd power gives a negative result. Note: -a^n is different from (-a)^n.",
        "visual_type": "exponent",
        "supported_by_visual_math": False,
        "example_question": "Simplify (-3)^2 and -3^2",
        "source_pdf": "Algebra 2.formulas.pdf",
        "page_number": 1,
        "status": "ready",
    },
    {
        "id": "alg2_power_fraction",
        "source_type": "formula",
        "course": "Algebra 2",
        "topic": "Powers of fractions",
        "title": "Power of a fraction",
        "formula_latex": "\\left( \\frac{a}{b} \\right)^c = \\frac{a^c}{b^c}",
        "formula_plain": "(a/b)^c = a^c / b^c",
        "description": "When raising a fraction to a power, raise both the numerator and the denominator to that power.",
        "visual_type": "exponent",
        "supported_by_visual_math": False,
        "example_question": "Simplify (2/3)^3",
        "source_pdf": "Algebra 2.formulas.pdf",
        "page_number": 2,
        "status": "ready",
    },
    {
        "id": "alg2_zero_exponent",
        "source_type": "formula",
        "course": "Algebra 2",
        "topic": "Zero exponent",
        "title": "Zero exponent rule",
        "formula_latex": "a^0 = 1 \\quad \\text{for } a \\neq 0",
        "formula_plain": "a^0 = 1 for a != 0",
        "description": "Any nonzero number raised to the power of zero equals 1. The expression 0^0 is undefined.",
        "visual_type": "exponent",
        "supported_by_visual_math": False,
        "example_question": "What is 5^0?",
        "source_pdf": "Algebra 2.formulas.pdf",
        "page_number": 3,
        "status": "ready",
    },
    {
        "id": "alg2_negative_exponent",
        "source_type": "formula",
        "course": "Algebra 2",
        "topic": "Negative exponents",
        "title": "Negative exponent rule",
        "formula_latex": "a^{-b} = \\frac{1}{a^b}",
        "formula_plain": "a^(-b) = 1 / a^b",
        "description": "A negative exponent means taking the reciprocal of the base raised to the positive exponent.",
        "visual_type": "exponent",
        "supported_by_visual_math": False,
        "example_question": "Simplify 2^(-3)",
        "source_pdf": "Algebra 2.formulas.pdf",
        "page_number": 4,
        "status": "ready",
    },
    {
        "id": "alg2_fractional_exponent",
        "source_type": "formula",
        "course": "Algebra 2",
        "topic": "Fractional exponents",
        "title": "Fractional exponent rule",
        "formula_latex": "x^{a/b} = \\sqrt[b]{x^a} = \\left( \\sqrt[b]{x} \\right)^a",
        "formula_plain": "x^(a/b) = b-th root of (x^a) = (b-th root of x)^a",
        "description": "A fractional exponent represents both a power and a root. The denominator is the root index and the numerator is the power.",
        "visual_type": "radical",
        "supported_by_visual_math": False,
        "example_question": "Simplify 8^(2/3)",
        "source_pdf": "Algebra 2.formulas.pdf",
        "page_number": 5,
        "status": "ready",
    },
    {
        "id": "alg2_radical_product",
        "source_type": "formula",
        "course": "Algebra 2",
        "topic": "Radical rules",
        "title": "Product rule for radicals",
        "formula_latex": "\\sqrt[n]{a} \\cdot \\sqrt[n]{b} = \\sqrt[n]{ab}",
        "formula_plain": "n-th root of a * n-th root of b = n-th root of (ab)",
        "description": "The product of two radicals with the same index is the radical of the product.",
        "visual_type": "radical",
        "supported_by_visual_math": False,
        "example_question": "Simplify sqrt(2) * sqrt(8)",
        "source_pdf": "Algebra 2.formulas.pdf",
        "page_number": 6,
        "status": "ready",
    },
    {
        "id": "alg2_radical_quotient",
        "source_type": "formula",
        "course": "Algebra 2",
        "topic": "Radical rules",
        "title": "Quotient rule for radicals",
        "formula_latex": "\\frac{\\sqrt[n]{a}}{\\sqrt[n]{b}} = \\sqrt[n]{\\frac{a}{b}}",
        "formula_plain": "n-th root of a / n-th root of b = n-th root of (a/b)",
        "description": "The quotient of two radicals with the same index is the radical of the quotient.",
        "visual_type": "radical",
        "supported_by_visual_math": False,
        "example_question": "Simplify sqrt(18) / sqrt(2)",
        "source_pdf": "Algebra 2.formulas.pdf",
        "page_number": 6,
        "status": "ready",
    },
    {
        "id": "alg2_rationalize_denominator",
        "source_type": "formula",
        "course": "Algebra 2",
        "topic": "Rationalizing denominator",
        "title": "Rationalizing the denominator",
        "formula_latex": "\\frac{1}{\\sqrt{a}} = \\frac{1}{\\sqrt{a}} \\cdot \\frac{\\sqrt{a}}{\\sqrt{a}} = \\frac{\\sqrt{a}}{a}",
        "formula_plain": "1/sqrt(a) = sqrt(a)/a",
        "description": "Remove a radical from the denominator by multiplying the numerator and denominator by that radical.",
        "visual_type": "radical",
        "supported_by_visual_math": False,
        "example_question": "Rationalize 1/sqrt(3)",
        "source_pdf": "Algebra 2.formulas.pdf",
        "page_number": 7,
        "status": "ready",
    },
    {
        "id": "alg2_rationalize_conjugate",
        "source_type": "formula",
        "course": "Algebra 2",
        "topic": "Rationalizing denominator",
        "title": "Rationalizing with conjugate",
        "formula_latex": "\\frac{1}{a + \\sqrt{b}} \\cdot \\frac{a - \\sqrt{b}}{a - \\sqrt{b}} = \\frac{a - \\sqrt{b}}{a^2 - b}",
        "formula_plain": "1/(a + sqrt(b)) * (a - sqrt(b))/(a - sqrt(b)) = (a - sqrt(b))/(a^2 - b)",
        "description": "When the denominator is a binomial containing a radical, multiply by its conjugate to create a rational denominator.",
        "visual_type": "radical",
        "supported_by_visual_math": False,
        "example_question": "Rationalize 1/(2 + sqrt(3))",
        "source_pdf": "Algebra 2.formulas.pdf",
        "page_number": 7,
        "status": "ready",
    },
    {
        "id": "alg2_exponential_function",
        "source_type": "formula",
        "course": "Algebra 2",
        "topic": "Exponential functions",
        "title": "Exponential function",
        "formula_latex": "f(x) = a \\cdot b^x",
        "formula_plain": "f(x) = a * b^x",
        "description": "An exponential function has a constant base b raised to a variable exponent x. The base must be positive and not equal to 1.",
        "visual_type": "exponential",
        "supported_by_visual_math": False,
        "example_question": "Evaluate f(2) if f(x) = 3 * 2^x",
        "source_pdf": "Algebra 2.formulas.pdf",
        "page_number": 8,
        "status": "ready",
    },
    {
        "id": "alg2_logarithm_definition",
        "source_type": "formula",
        "course": "Algebra 2",
        "topic": "Logarithms",
        "title": "Logarithm definition",
        "formula_latex": "\\log_b(a) = c \\iff b^c = a",
        "formula_plain": "log_b(a) = c if and only if b^c = a",
        "description": "A logarithm answers the question: 'To what power must the base b be raised to get a?'",
        "visual_type": "exponential",
        "supported_by_visual_math": False,
        "example_question": "Evaluate log_2(8)",
        "source_pdf": "Algebra 2.formulas.pdf",
        "page_number": 9,
        "status": "ready",
    },
    {
        "id": "alg2_change_of_base",
        "source_type": "formula",
        "course": "Algebra 2",
        "topic": "Logarithms",
        "title": "Change of base formula",
        "formula_latex": "\\log_b(a) = \\frac{\\log_c(a)}{\\log_c(b)}",
        "formula_plain": "log_b(a) = log_c(a) / log_c(b)",
        "description": "Allows you to evaluate a logarithm in any base using a calculator with a different base (usually base 10 or base e).",
        "visual_type": "exponential",
        "supported_by_visual_math": False,
        "example_question": "Evaluate log_3(7) using the change of base formula",
        "source_pdf": "Algebra 2.formulas.pdf",
        "page_number": 10,
        "status": "ready",
    },
    # =====================================================================
    # Extra records to reach >65
    # =====================================================================
    {
        "id": "prea_percent_basic",
        "source_type": "formula",
        "course": "Pre-Algebra",
        "topic": "Percent basics",
        "title": "Percent to decimal",
        "formula_latex": "p\\% = \\frac{p}{100}",
        "formula_plain": "p% = p / 100",
        "description": "To convert a percent to a decimal, divide by 100.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Convert 25% to a decimal",
        "source_pdf": "Pre-Algebra.formulas.pdf",
        "page_number": 7,
        "status": "ready",
    },
    {
        "id": "alg1_zero_product_property",
        "source_type": "formula",
        "course": "Algebra 1",
        "topic": "Factoring",
        "title": "Zero Product Property",
        "formula_latex": "\\text{If } ab = 0, \\text{ then } a = 0 \\text{ or } b = 0",
        "formula_plain": "If ab = 0, then a = 0 or b = 0",
        "description": "If the product of two factors is zero, at least one of the factors must be zero. This is the basis for solving equations by factoring.",
        "visual_type": "polynomial",
        "supported_by_visual_math": False,
        "example_question": "Solve (x - 3)(x + 2) = 0",
        "source_pdf": "Algebra 1.formulas.pdf",
        "page_number": 11,
        "status": "ready",
    },
    {
        "id": "geo_volume_cylinder",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Volume",
        "title": "Volume of a cylinder",
        "formula_latex": "V = \\pi r^2 h",
        "formula_plain": "V = pi * r^2 * h",
        "description": "The volume of a cylinder is the area of its circular base times its height.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Find the volume of a cylinder with radius 3 and height 5",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 15,
        "status": "ready",
    },
    {
        "id": "geo_surface_area_sphere",
        "source_type": "formula",
        "course": "Geometry",
        "topic": "Surface area",
        "title": "Surface area of a sphere",
        "formula_latex": "SA = 4\\pi r^2",
        "formula_plain": "SA = 4 * pi * r^2",
        "description": "The surface area of a sphere is 4 times pi times the square of its radius.",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "Find the surface area of a sphere with radius 2",
        "source_pdf": "Geometry.formulas.pdf",
        "page_number": 15,
        "status": "ready",
    },
    {
        "id": "linalg_cramers_rule",
        "source_type": "formula",
        "course": "Linear Algebra",
        "topic": "Determinants",
        "title": "Cramer's Rule",
        "formula_latex": "x = \\frac{\\det(A_x)}{\\det(A)} \\quad ; \\quad y = \\frac{\\det(A_y)}{\\det(A)}",
        "formula_plain": "x = det(Ax) / det(A); y = det(Ay) / det(A)",
        "description": "A method for solving a system of linear equations using determinants. Replace the column of coefficients for the variable with the constants.",
        "visual_type": "matrix",
        "supported_by_visual_math": False,
        "example_question": "Solve a 2x2 system using Cramer's Rule",
        "source_pdf": "Linear Algebra.formulas.pdf",
        "page_number": 9,
        "status": "ready",
    },
    {
        "id": "alg2_complex_numbers",
        "source_type": "formula",
        "course": "Algebra 2",
        "topic": "Complex numbers",
        "title": "Complex number form",
        "formula_latex": "z = a + bi",
        "formula_plain": "z = a + bi",
        "description": "A complex number has a real part a and an imaginary part bi, where i = sqrt(-1).",
        "visual_type": "concept_card",
        "supported_by_visual_math": False,
        "example_question": "What is the real part of 3 + 4i?",
        "source_pdf": "Algebra 2.formulas.pdf",
        "page_number": 11,
        "status": "ready",
    },
]

FORMULA_COUNT = len(EMBEDDED_FORMULA_LIBRARY)
