# -*- coding: utf-8 -*-
"""Math Course AI — ortak temel katman.

Ana dosyadan (Math_Course_AI.pyw) V48'de mekanik olarak cikarildi:
uygulama kimligi/yollari, model varsayilanlari, kucuk yardimcilar,
THEME/DARK_THEME paletleri ve RoundedButton. Ana dosya .pyw olarak
__main__ adiyla kostugu icin diger moduller oradan import YAPAMAZ —
paylasilan her sey bu modulde yasar.

Kural: Buradaki kod ana dosyadan satiri satirina tasinmistir; davranis
degisikligi iceren duzenlemeler ayri commit'lerde yapilir.
"""

import os
import re
import sys
import json
import time
import math
from pathlib import Path
from datetime import datetime
import tkinter as tk

import app_paths

try:
    import fitz  # PyMuPDF — read_text_file'in PDF yolu icin
except Exception:
    fitz = None

# docx da ayni sebeple tembel yuklenir (~0.14 sn, tek kullanici read_file_text).
_docx_cache = []

def _lazy_docx():
    if not _docx_cache:
        try:
            import docx as _dx
            _docx_cache.append(_dx)
        except Exception:
            _docx_cache.append(None)
    return _docx_cache[0]

# pytesseract acilista IMPORT EDILMEZ: paketi pandas'i da surukleyip tek
# basina ~0.7 sn tutuyor ve OCR yalnizca "gorsel soru coz" akisinda lazim.
# Kullanan tek yer (try_ocr_image) _lazy_pytesseract() ile yukler; kurulu
# degilse None doner ve davranis eskisiyle ayni kalir.
_pytesseract_cache = []

def _lazy_pytesseract():
    if not _pytesseract_cache:
        try:
            import pytesseract as _pt
            _pytesseract_cache.append(_pt)
        except Exception:
            _pytesseract_cache.append(None)
    return _pytesseract_cache[0]



# ══════════════════════════════════════════════════════════════════════════
# OUTBOUND URL GUARD
# ══════════════════════════════════════════════════════════════════════════
#: The only URL schemes this program will ever open. The AI base URL is
#: user-configurable, and urllib happily opens file:// and ftp:// — a pasted
#: or mistyped base URL must not turn into a local-file read.
ALLOWED_URL_SCHEMES = ("http", "https")


class UnsafeUrlError(ValueError):
    """Raised when a URL uses a scheme this program refuses to open."""


def guard_url(url):
    """Return `url` if it is an http(s) URL, else raise UnsafeUrlError.

    Pure and testable; every urlopen call site in this program goes through it.
    """
    from urllib.parse import urlparse
    metin = str(url or "").strip()
    try:
        parca = urlparse(metin)
    except Exception as exc:
        raise UnsafeUrlError("URL cozumlenemedi / unparseable URL") from exc
    if parca.scheme.lower() not in ALLOWED_URL_SCHEMES:
        raise UnsafeUrlError(
            "yalnizca http/https acilir, gelen: %r / only http(s) may be opened"
            % (parca.scheme or "(bos)"))
    if not parca.netloc:
        raise UnsafeUrlError("URL sunucu adi tasimiyor / URL has no host")
    return metin

APP_NAME = "Math Course AI"
VERSION = "V48 — AI Terminali, Koyu Tema & Modül Bölünmesi"
DEFAULT_RESOURCE_DIR = str(app_paths.resources_dir())
DEFAULT_BASE_URL = "http://127.0.0.1:1234"
DEFAULT_MODEL = "qwen2.5-math-7b-instruct"
DEFAULT_MATH_MODEL = "qwen2.5-math-7b-instruct"
DEFAULT_SCIENCE_MODEL = "qwen/qwen3-vl-8b"
DEFAULT_PHYSICS_MODEL = "qwen/qwen3-vl-8b"
DEFAULT_CHEMISTRY_MODEL = "lmstudio-community/Mistral-Small-3.2-24B-Instruct-2506-GGUF"
DEFAULT_DNA_MODEL = "MaziyarPanahi/BioMistral-7B-GGUF-Q5_K_M"
DEFAULT_CODE_MODEL = "deepseek-coder-v2-lite-instruct"
DEFAULT_VISION_MODEL = "auto"
ICON_FILENAME = "math_course_ai_icon.ico"

def resource_path(relative_path):
    """Return a path that works both in development and in a PyInstaller one-file EXE."""
    try:
        base_path = Path(sys._MEIPASS)  # type: ignore[attr-defined]
    except Exception:
        base_path = Path(__file__).resolve().parent
    return str(base_path / relative_path)

_APPDATA_ROOT = Path(os.getenv("APPDATA") or Path.home())
APP_FOLDER = _APPDATA_ROOT / "MathCourseAI"
APP_FOLDER.mkdir(parents=True, exist_ok=True)
CONFIG_PATH = APP_FOLDER / "config_v22.json"
PROGRESS_PATH = APP_FOLDER / "course_progress_v22.json"
TOKEN_LOG_PATH = APP_FOLDER / "token_usage_v22.jsonl"
# ℹ topic explanations ("Nedir ve Ne İçin Kullanılır?") generated by the local
# AI are cached here so they open instantly and work offline afterwards.
TOPIC_INFO_CACHE_PATH = APP_FOLDER / "topic_info_cache.json"
ANNOTATION_DIR = APP_FOLDER / "annotations"
ANNOTATION_DIR.mkdir(parents=True, exist_ok=True)

SUPPORTED_EXTS = {".pdf", ".txt", ".md", ".rtf", ".docx", ".fa", ".fasta", ".fna", ".dna"}
IGNORED_NAME_PATTERNS = ["read me", "readme", ".ds_store", "__macosx"]
# Course-tree ordering.
#
# This used to be a hardcoded list of one particular commercial course
# catalogue's product titles, which meant the ordering only worked for the
# original author's folder layout and baked a third party's brand into the
# source. It is now keyed on SUBJECT keywords, so any course folder in any
# language sorts into a sensible teaching order, and a user can override it
# with their own list (see course_order_keywords()).
#
# Ordered from the earliest topic to the latest; each entry is a group of
# equivalent keywords, matched case-insensitively with "&" folded to "and".
COURSE_ORDER_KEYWORDS = [
    ("fundamentals of math", "basic math", "arithmetic", "foundations",
     "pre-algebra", "prealgebra", "temel matematik", "matematige giris"),
    ("algebra 1", "algebra i", "cebir 1", "algebra"),
    ("algebra 2", "algebra ii", "cebir 2"),
    ("geometry", "geometri"),
    ("trigonometry", "precalculus", "pre-calculus", "trigonometri"),
    ("linear algebra", "lineer cebir", "dogrusal cebir"),
    ("calculus 1", "calculus i", "analiz 1"),
    ("calculus 2", "calculus ii", "analiz 2"),
    ("calculus 3", "calculus iii", "multivariable", "analiz 3"),
    ("differential equations", "diferansiyel denklemler"),
    ("probability", "statistics", "olasilik", "istatistik"),
    ("data science", "machine learning", "veri bilimi"),
]

#: File a user may drop next to the program to override the ordering: one
#: keyword per line, earliest topic first. Missing file = the default above.
COURSE_ORDER_FILE = "course_order.txt"

# Warm, airy light theme ("Sıcak Çalışma" / Direction 2).
# Paper-toned neutrals + amber accent for a student-friendly, scientific feel.
THEME = {
    "bg": "#F3EBE0",       # warm canvas behind panels
    "panel": "#FBF7F1",    # paper surface for most frames/headers
    "panel2": "#F6EFE4",   # warm sand for rails / secondary surfaces
    "text": "#2B2620",     # near-black warm ink
    "muted": "#8A7E6E",    # muted warm gray
    "accent": "#E07B39",   # amber primary
    "green": "#16A55A",    # success / save
    "purple": "#8b5cf6",
    "danger": "#C0392B",
    "line": "#ECE3D8",     # warm hairline borders
    "border": "#D8C9B6",   # visible input/edge border (crisper than line)
    "surface": "#FFFFFF",  # pure white input surfaces (text areas, lists)
    "accent_soft": "#FBEADD",  # amber tint for hover/selection
    "canvas": "#EDE6DB",   # PDF viewer backdrop (page sits on this)
}

# Karanlik tema paleti: ayni "sicak" kimligin gece hali (amber vurgu korunur).
# Acilista config["theme"]=="dark" ise THEME.update(DARK_THEME) yapilir —
# tum widget'lar rengini kurulum aninda THEME'den okudugu icin tek mutasyon
# yeter; canli gecis bilerek yok (yeniden baslatma notu gosterilir).
DARK_THEME = {
    "bg": "#201B15",
    "panel": "#2A241C",
    "panel2": "#332C22",
    "text": "#EDE5D8",
    "muted": "#A6987F",
    "accent": "#E07B39",
    "green": "#2FBF71",
    "purple": "#a78bfa",
    "danger": "#E25B4A",
    "line": "#3A3226",
    "border": "#4A4033",
    "surface": "#1B1712",
    "accent_soft": "#4A3423",
    "canvas": "#26211A",
}



# ══════════════════════════════════════════════════════════════════════════
# İKİ DİLLİLİK (TR/EN) — paylaşılan ince katman
# ══════════════════════════════════════════════════════════════════════════
#
# Ana dosyanın kendi UI_TEXT sözlüğü var; yardımcı modüller (Öğrenci Takip,
# laboratuvarlar, terminal, hesap makinesi…) V48'e kadar Türkçe sabit metin
# kullanıyordu. Her modüle ayrı bir çeviri makinesi yazmak yerine tek bir
# yardımcı: metin ÇİFTİ yerinde durur, dil seçimi tek satırda yapılır.
#
#     tk.Label(f, text=t2("Kaydet", "Save", lang))
#
# Neden sözlük+anahtar değil: anahtar tabanlı sistemde metin koddan uzaklaşır
# ve eşleşmeyen anahtar sessizce boş etiket üretir. Çift yerinde durunca
# "hangi metin" sorusu okurken cevaplanır ve bir dil unutulamaz.


def normalize_lang(lang):
    """'English', 'en-US', 'EN' → 'en'; geri kalan her şey → 'tr'."""
    return "en" if str(lang or "").strip().lower().startswith("en") else "tr"


def t2(tr, en, lang="tr"):
    """İki dilli metin seçici. Boş İngilizce verilirse Türkçesine düşer."""
    if normalize_lang(lang) == "en":
        return en if (en is not None and str(en) != "") else tr
    return tr


def app_lang(app, default="tr"):
    """Bir panelin sahibi uygulamadan dilini güvenle okur.

    Panel testlerde sahte bir `app` ile de kurulabildiği için hata yutulur.
    """
    try:
        return normalize_lang(getattr(app, "language", default))
    except Exception:
        return normalize_lang(default)


def safe_json_load(path, default):
    try:
        if Path(path).exists():
            return json.loads(Path(path).read_text(encoding="utf-8"))
    except Exception:
        pass
    return default


def safe_json_save(path, data):
    try:
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        Path(path).write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    except Exception as exc:
        print("Save error:", exc)


def now_iso():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def strip_rtf(text):
    """Small RTF-to-text fallback good enough for READ ME files."""
    if not text:
        return ""
    # decode common escaped hex chars
    def repl_hex(m):
        try:
            return bytes.fromhex(m.group(1)).decode("cp1252", errors="ignore")
        except Exception:
            return ""
    text = re.sub(r"\\'([0-9a-fA-F]{2})", repl_hex, text)
    text = re.sub(r"\\par[d]?", "\n", text)
    text = re.sub(r"\\tab", "\t", text)
    text = re.sub(r"\{\\\*[^{}]*\}", "", text)
    text = re.sub(r"\\[a-zA-Z]+-?\d* ?", "", text)
    text = text.replace("{", "").replace("}", "")
    text = text.replace("\\", "")
    text = re.sub(r"\n\s*\n\s*\n+", "\n\n", text)
    return text.strip()


def read_text_file(path, max_chars=250_000):
    path = Path(path)
    ext = path.suffix.lower()
    try:
        if ext == ".rtf":
            raw = path.read_text(encoding="utf-8", errors="ignore")
            return strip_rtf(raw)[:max_chars]
        if ext in {".txt", ".md"}:
            return path.read_text(encoding="utf-8", errors="ignore")[:max_chars]
        if ext == ".docx" and _lazy_docx():
            document = _lazy_docx().Document(str(path))
            text = "\n".join(p.text for p in document.paragraphs)
            return text[:max_chars]
        if ext == ".pdf" and fitz:
            out = []
            with fitz.open(str(path)) as doc:
                for i, page in enumerate(doc):
                    if i >= 30:
                        out.append("\n[Text extraction stopped after 30 pages for safety.]\n")
                        break
                    out.append(f"\n--- Page {i+1} ---\n" + page.get_text("text"))
            return "\n".join(out)[:max_chars]
    except Exception as exc:
        return f"Could not read file: {exc}"
    return "This file type can be opened externally, but text extraction is not available."


def short_name(path, limit=65):
    name = Path(path).name
    return name if len(name) <= limit else name[:limit - 3] + "..."


def natural_key(value):
    s = str(value).lower()
    return [int(part) if part.isdigit() else part for part in re.split(r"(\d+)", s)]


def is_ignored_resource(path):
    name = Path(path).name.lower()
    if name.startswith("."):
        return True
    return any(pat in name for pat in IGNORED_NAME_PATTERNS)


def course_order_keywords():
    """The active ordering: the user's course_order.txt if present, else the default.

    A user's file wins so nobody has to edit the source to make their own
    folder names sort correctly.
    """
    try:
        yol = Path(app_paths.resources_dir()) / COURSE_ORDER_FILE
        if yol.is_file():
            satirlar = [s.strip().lower() for s in
                        yol.read_text(encoding="utf-8").splitlines()]
            gruplar = [(s,) for s in satirlar if s and not s.startswith("#")]
            if gruplar:
                return gruplar
    except Exception:
        pass
    return COURSE_ORDER_KEYWORDS


def course_key(name):
    """Sort key for a course folder: (teaching-order index, lowercased name).

    The MOST SPECIFIC keyword wins, not the first one listed — otherwise
    "Linear Algebra" would be caught by the plain "algebra" group and sort
    before Geometry. Unmatched folders sort last, alphabetically, instead of
    being silently reordered.
    """
    n = name.lower().replace("&", "and")
    en_iyi = None                      # (-keyword_length, index)
    for idx, grup in enumerate(course_order_keywords()):
        for key in grup:
            k = key.replace("&", "and")
            if k in n:
                aday = (-len(k), idx)
                if en_iyi is None or aday < en_iyi:
                    en_iyi = aday
    return (en_iyi[1] if en_iyi else 99, name.lower())


def estimate_tokens(text):
    return max(1, math.ceil(len(text or "") / 4))


def safe_output_tokens(prompt, kind="answer"):
    p = estimate_tokens(prompt)
    if kind == "test":
        return 64
    if kind == "resource":
        return min(900, max(420, 1600 - p // 2))
    return min(1100, max(500, 1800 - p // 2))


class RoundedButton(tk.Canvas):
    """A soft, rounded-corner button drawn on a Canvas (pure Tkinter).

    ttk/clam buttons have hard square corners; this gives the warm, pill-shaped
    look of the "Sıcak Çalışma" design. Supports hover, press, disabled state,
    fill="x" stretching, and .config(text=...) for live language switching.
    """

    def __init__(self, master, text="", command=None, radius=14,
                 bg=None, fg=None, hover=None, parent_bg=None,
                 font=("Segoe UI Semibold", 9), padx=13, pady=7, style=None,
                 takefocus=None, width=None, **kw):
        import tkinter.font as _tkfont
        # Translate ttk-style kwargs so a blanket ttk.Button -> RoundedButton
        # swap works without per-call edits.
        if style == "Calc.TButton":
            # Sabit beyaz degil THEME yuzeyi: koyu temada beyaz tus ustune
            # fildisi metin okunmuyordu (ekran dogrulamasinda yakalandi).
            bg = bg or THEME["surface"]
            font = ("Segoe UI Semibold", 13)
            padx, pady, radius = 10, 12, 12
        elif style == "Accent.TButton":
            bg = bg or THEME["accent"]; fg = fg or "#FFFFFF"; hover = hover or "#EC8A4B"
        elif style == "Save.TButton":
            bg = bg or THEME["green"]; fg = fg or "#FFFFFF"; hover = hover or "#23B768"
        _char_w = None
        if isinstance(width, int):
            _char_w = width  # ttk width is in characters; approximate below
        if parent_bg is None:
            parent_bg = THEME["panel"]
        super().__init__(master, bd=0, highlightthickness=0, bg=parent_bg,
                         takefocus=0, cursor="hand2", **kw)
        self._command = command
        self._radius = radius
        self._bg = bg or THEME["panel2"]
        self._fg = fg or THEME["text"]
        self._hover = hover or THEME["accent_soft"]
        self._font = _tkfont.Font(family=font[0], size=font[1],
                                  weight=("bold" if len(font) > 2 and font[2] == "bold" else "normal"))
        self._padx = padx
        self._pady = pady
        self._text = text
        self._state = "normal"
        self._fill = self._bg
        tw = self._font.measure(text or "")
        if _char_w:
            tw = max(tw, self._font.measure("0") * _char_w)
        th = self._font.metrics("linespace")
        self._req_w = tw + padx * 2
        self._req_h = th + pady * 2
        self.configure(width=self._req_w, height=self._req_h)
        self.bind("<Configure>", lambda e: self._render())
        self.bind("<Enter>", self._on_enter)
        self.bind("<Leave>", self._on_leave)
        self.bind("<ButtonPress-1>", self._on_press)
        self.bind("<ButtonRelease-1>", self._on_release)
        self._render()

    def _round_rect(self, x1, y1, x2, y2, r, **kw):
        r = max(0, min(r, (x2 - x1) // 2, (y2 - y1) // 2))
        pts = [
            x1 + r, y1, x2 - r, y1, x2, y1, x2, y1 + r, x2, y2 - r, x2, y2,
            x2 - r, y2, x1 + r, y2, x1, y2, x1, y2 - r, x1, y1 + r, x1, y1,
        ]
        return self.create_polygon(pts, smooth=True, **kw)

    def _render(self, fill=None):
        if fill is not None:
            self._fill = fill
        self.delete("all")
        w = self.winfo_width() or self._req_w
        h = self.winfo_height() or self._req_h
        if w <= 1:
            w = self._req_w
        if h <= 1:
            h = self._req_h
        self._round_rect(1, 1, w - 1, h - 1, self._radius,
                         fill=self._fill, outline=self._fill)
        fg = self._fg if self._state == "normal" else THEME["muted"]
        self.create_text(w // 2, h // 2, text=self._text, fill=fg, font=self._font)

    def _on_enter(self, _e):
        if self._state == "normal":
            self._render(self._hover)

    def _on_leave(self, _e):
        if self._state == "normal":
            self._render(self._bg)

    def _on_press(self, _e):
        if self._state == "normal":
            self._render(self._bg)

    def _on_release(self, _e):
        if self._state == "normal":
            self._render(self._hover)
            if callable(self._command):
                self._command()

    def configure(self, **kw):
        kw.pop("style", None)
        kw.pop("takefocus", None)
        if "text" in kw:
            self._text = kw.pop("text")
        if "command" in kw:
            self._command = kw.pop("command")
        if "state" in kw:
            self._state = "disabled" if kw.pop("state") in ("disabled", "disable") else "normal"
        if "bg" in kw:
            self._bg = kw.pop("bg")
            self._fill = self._bg
        if kw:
            super().configure(**kw)
        if self.winfo_exists():
            self._render()

    config = configure


