# -*- coding: utf-8 -*-
"""
Question Packs / Soru Paketleri
===============================

LICENSE NOTE — read this before adding content
----------------------------------------------
Turkish question banks (MEB / EBA / OGM Materyal / ÖSYM archives) and every
commercial publisher's "soru bankası" are **copyrighted**. They are deliberately
NOT bundled here — redistributing them inside this program would be a copyright
violation.

So this module ships two legal sources instead:

1. **Built-in procedural generators (default).** Every question *and* its exact
   answer is produced by original code in this file. The content is therefore
   ours, unlimited, bilingual (TR/EN), and carries no third-party licence. This
   is what fills the Turkish gap legally.

2. **External packs you download yourself.** Drop an openly-licensed pack as
   JSON into `question_packs/` and it appears in the picker. The pack's
   `license` + `attribution` are stored on every imported question, so
   attribution requirements (e.g. CC BY) are preserved inside the app.

   Known-good, openly licensed English sources (verified 2026-06):
     • nvidia/OpenMathInstruct-1 ......... CC BY 4.0   (attribution required)
     • google-deepmind/mathematics_dataset  Apache-2.0 (a generator, not data)
     • Kaggle "Mathematical Problems" .... CC0 1.0    (public domain)
     • UCI MathE ......................... CC BY 4.0
   Always re-check a source's licence before importing it.
"""

import json
import random
import shutil
import zipfile
from fractions import Fraction
from pathlib import Path

# ── .mcpack: gorselli paket bicimi (V48) ───────────────────────────────────
# Duz .json paket metin tabanliydi; ✂ ile kirpilmis GORSEL sorular dışa
# aktarmada atlaniyordu. .mcpack tek bir ZIP icinde
#     paket.json  +  images/<dosya>.png
# tasir. Soru kaydina "image": "images/x.png" alani eklenir.
# ESKI DUZ .json PAKETLER AYNEN CALISIR — yukleyici ikisini de okur.
MCPACK_UZANTI = ".mcpack"
MCPACK_JSON = "paket.json"
MCPACK_IMAGES = "images"
# Guvenlik: zip icindeki gorsel yollari yalnizca images/ altinda ve duz
# olmali. "../" ya da mutlak yol iceren bir paket dosya sistemine tasamaz.
_GECERLI_GORSEL_UZANTI = {".png", ".jpg", ".jpeg", ".gif", ".bmp", ".webp"}


def _guvenli_gorsel_adi(rel):
    """ZIP icindeki gorsel yolunu dogrular → dosya adi ya da None.

    Kabul: 'images/xyz.png'. Red: mutlak yol, '..', alt klasor, tanimadigi
    uzanti. Kotu niyetli ya da bozuk bir paket disari yazamasin diye.
    """
    rel = str(rel or "").replace("\\", "/").strip()
    if not rel or not rel.startswith(MCPACK_IMAGES + "/"):
        return None
    ad = rel[len(MCPACK_IMAGES) + 1:]
    if not ad or "/" in ad or ad in (".", "..") or ad.startswith("."):
        return None
    if Path(ad).suffix.lower() not in _GECERLI_GORSEL_UZANTI:
        return None
    return ad


def _gorsel_hedef_klasoru():
    """Ice aktarilan gorsellerin gidecegi klasor (student_tracker ile AYNI).

    app_paths uzerinden hesaplanir; student_tracker'i import etmek dongu
    yaratirdi (o zaten bu modulu import ediyor).
    """
    try:
        from app_paths import DATA_DIR
        d = Path(DATA_DIR) / "question_images"
    except Exception:
        d = Path.home() / ".mathcourseai" / "question_images"
    try:
        d.mkdir(parents=True, exist_ok=True)
    except Exception:
        pass
    return d

# External packs are program content (not user data): they live next to the
# program. app_paths resolves this correctly for both source and EXE runs.
try:
    from app_paths import packs_dir
    PACKS_DIR = packs_dir()
except Exception:  # pragma: no cover — headless fallback
    PACKS_DIR = Path(__file__).resolve().parent / "question_packs"

BUILTIN_LICENSE = "Original content — generated by Math Course AI (no third-party licence)"
BUILTIN_ATTRIBUTION = "Math Course AI — built-in generator"

DIFFICULTIES = ("Easy", "Medium", "Hard")


def _t(lang, tr, en):
    return tr if lang == "tr" else en


def _frac_str(f):
    f = Fraction(f).limit_denominator(10000)
    return str(f.numerator) if f.denominator == 1 else f"{f.numerator}/{f.denominator}"


# ===========================================================================
# Procedural generators — each returns (question, answer, topic, difficulty)
# ===========================================================================
def gen_arithmetic(rng, lang):
    a, b = rng.randint(2, 99), rng.randint(2, 99)
    op = rng.choice(["+", "-", "*"])
    val = {"+": a + b, "-": a - b, "*": a * b}[op]
    return (f"{a} {op} {b} = ?", str(val),
            _t(lang, "Dört İşlem", "Arithmetic"), "Easy")


def gen_order_of_operations(rng, lang):
    a, b, c, d = (rng.randint(2, 12) for _ in range(4))
    q = f"{a} + {b} × {c} − {d} = ?"
    return (q, str(a + b * c - d), _t(lang, "İşlem Önceliği", "Order of Operations"), "Easy")


def gen_integers(rng, lang):
    a, b = rng.randint(-40, -2), rng.randint(2, 40)
    op = rng.choice(["+", "-", "*"])
    val = {"+": a + b, "-": a - b, "*": a * b}[op]
    return (f"({a}) {op} ({b}) = ?", str(val), _t(lang, "Tam Sayılar", "Integers"), "Easy")


def gen_fractions(rng, lang):
    a, b, c, d = rng.randint(1, 9), rng.randint(2, 9), rng.randint(1, 9), rng.randint(2, 9)
    op = rng.choice(["+", "-", "*"])
    f1, f2 = Fraction(a, b), Fraction(c, d)
    val = {"+": f1 + f2, "-": f1 - f2, "*": f1 * f2}[op]
    return (f"{a}/{b} {op} {c}/{d} = ?  " + _t(lang, "(sadeleştir)", "(simplify)"),
            _frac_str(val), _t(lang, "Kesirler", "Fractions"), "Medium")


def gen_percentage(rng, lang):
    p, n = rng.choice([5, 10, 12, 15, 20, 25, 40, 50]), rng.randint(2, 40) * 10
    val = Fraction(p, 100) * n
    return (_t(lang, f"{n} sayısının %{p} kaçtır?", f"What is {p}% of {n}?"),
            _frac_str(val), _t(lang, "Yüzde", "Percentage"), "Easy")


def gen_linear_equation(rng, lang):
    a = rng.randint(2, 12)
    x = rng.randint(-9, 9)
    b = rng.randint(-20, 20)
    c = a * x + b
    sign = "+" if b >= 0 else "−"
    q = _t(lang, f"{a}x {sign} {abs(b)} = {c} denkleminde x kaçtır?",
           f"Solve for x:  {a}x {sign} {abs(b)} = {c}")
    return (q, f"x = {x}", _t(lang, "Birinci Derece Denklem", "Linear Equations"), "Medium")


def gen_quadratic(rng, lang):
    r1, r2 = rng.randint(-8, 8), rng.randint(-8, 8)
    b, c = -(r1 + r2), r1 * r2
    bs = f"+ {b}x" if b > 0 else (f"− {abs(b)}x" if b < 0 else "")
    cs = f"+ {c}" if c > 0 else (f"− {abs(c)}" if c < 0 else "")
    q = _t(lang, f"x² {bs} {cs} = 0 denkleminin kökleri nedir?",
           f"Find the roots:  x² {bs} {cs} = 0")
    roots = sorted({r1, r2})
    return (q, "x = " + ", ".join(str(r) for r in roots),
            _t(lang, "İkinci Derece Denklem", "Quadratic Equations"), "Hard")


def gen_system2(rng, lang):
    x, y = rng.randint(-6, 6), rng.randint(-6, 6)
    a1, b1, a2, b2 = (rng.randint(1, 6) for _ in range(4))
    if a1 * b2 - a2 * b1 == 0:
        b2 += 1
    c1, c2 = a1 * x + b1 * y, a2 * x + b2 * y
    q = _t(lang, f"Sistemi çöz:  {a1}x + {b1}y = {c1}   ve   {a2}x + {b2}y = {c2}",
           f"Solve the system:  {a1}x + {b1}y = {c1}   and   {a2}x + {b2}y = {c2}")
    return (q, f"x = {x}, y = {y}", _t(lang, "Denklem Sistemi", "Systems of Equations"), "Hard")


def gen_exponent(rng, lang):
    a, m, n = rng.randint(2, 6), rng.randint(2, 5), rng.randint(2, 5)
    q = _t(lang, f"{a}^{m} × {a}^{n} = ?  (tek üs olarak sadeleştir ve değeri yaz)",
           f"Simplify and evaluate:  {a}^{m} × {a}^{n} = ?")
    return (q, f"{a}^{m + n} = {a ** (m + n)}", _t(lang, "Üslü Sayılar", "Exponents"), "Medium")


def gen_slope(rng, lang):
    x1, y1 = rng.randint(-8, 8), rng.randint(-8, 8)
    x2, y2 = rng.randint(-8, 8), rng.randint(-8, 8)
    if x1 == x2:
        x2 += 1
    m = Fraction(y2 - y1, x2 - x1)
    q = _t(lang, f"A({x1}, {y1}) ve B({x2}, {y2}) noktalarından geçen doğrunun eğimi nedir?",
           f"Find the slope of the line through A({x1}, {y1}) and B({x2}, {y2}).")
    return (q, f"m = {_frac_str(m)}", _t(lang, "Eğim", "Slope"), "Medium")


def gen_rect_area(rng, lang):
    a, b = rng.randint(3, 25), rng.randint(3, 25)
    if rng.random() < 0.5:
        q = _t(lang, f"Kenarları {a} ve {b} olan dikdörtgenin alanı kaçtır?",
               f"Find the area of a rectangle with sides {a} and {b}.")
        return (q, str(a * b), _t(lang, "Alan", "Area"), "Easy")
    q = _t(lang, f"Kenarları {a} ve {b} olan dikdörtgenin çevresi kaçtır?",
           f"Find the perimeter of a rectangle with sides {a} and {b}.")
    return (q, str(2 * (a + b)), _t(lang, "Çevre", "Perimeter"), "Easy")


def gen_pythagoras(rng, lang):
    k = rng.randint(1, 6)
    a, b, c = rng.choice([(3, 4, 5), (5, 12, 13), (8, 15, 17), (7, 24, 25)])
    a, b, c = a * k, b * k, c * k
    q = _t(lang, f"Dik kenarları {a} ve {b} olan dik üçgenin hipotenüsü kaçtır?",
           f"A right triangle has legs {a} and {b}. Find the hypotenuse.")
    return (q, str(c), _t(lang, "Pisagor", "Pythagorean Theorem"), "Medium")


def gen_circle(rng, lang):
    r = rng.randint(2, 15)
    if rng.random() < 0.5:
        q = _t(lang, f"Yarıçapı {r} olan çemberin alanı nedir? (π cinsinden)",
               f"Find the area of a circle with radius {r}. (in terms of π)")
        return (q, f"{r * r}π", _t(lang, "Çember", "Circles"), "Medium")
    q = _t(lang, f"Yarıçapı {r} olan çemberin çevresi nedir? (π cinsinden)",
           f"Find the circumference of a circle with radius {r}. (in terms of π)")
    return (q, f"{2 * r}π", _t(lang, "Çember", "Circles"), "Medium")


def gen_matrix_det2(rng, lang):
    a, b, c, d = (rng.randint(-9, 9) for _ in range(4))
    q = _t(lang, f"[[{a}, {b}], [{c}, {d}]] matrisinin determinantı nedir?",
           f"Find the determinant of [[{a}, {b}], [{c}, {d}]].")
    return (q, str(a * d - b * c), _t(lang, "Determinant", "Determinants"), "Medium")


def gen_matrix_add(rng, lang):
    m1 = [[rng.randint(-9, 9) for _ in range(2)] for _ in range(2)]
    m2 = [[rng.randint(-9, 9) for _ in range(2)] for _ in range(2)]
    s = [[m1[i][j] + m2[i][j] for j in range(2)] for i in range(2)]
    q = _t(lang, f"{m1} + {m2} = ?  (matris toplamı)", f"Compute the matrix sum: {m1} + {m2}")
    return (q, str(s), _t(lang, "Matris Toplama", "Matrix Addition"), "Easy")


def gen_dot_product(rng, lang):
    u = [rng.randint(-9, 9) for _ in range(3)]
    v = [rng.randint(-9, 9) for _ in range(3)]
    q = _t(lang, f"u = {u} ve v = {v} vektörlerinin skaler (nokta) çarpımı nedir?",
           f"Find the dot product of u = {u} and v = {v}.")
    return (q, str(sum(a * b for a, b in zip(u, v))),
            _t(lang, "Nokta Çarpım", "Dot Product"), "Medium")


def gen_derivative_poly(rng, lang):
    a, n, b = rng.randint(2, 9), rng.randint(2, 5), rng.randint(1, 9)
    q = _t(lang, f"f(x) = {a}x^{n} + {b}x  fonksiyonunun türevi nedir?",
           f"Find the derivative of f(x) = {a}x^{n} + {b}x.")
    ns = f"{a * n}x^{n - 1}" if n - 1 > 1 else f"{a * n}x"
    return (q, f"f'(x) = {ns} + {b}", _t(lang, "Türev", "Derivatives"), "Medium")


# ===========================================================================
# Built-in packs
# ===========================================================================
BUILTIN_PACKS = [
    {
        "id": "prealgebra_core",
        "name_tr": "Pre-Algebra Temel (üretilmiş)",
        "name_en": "Pre-Algebra Core (generated)",
        "course": "Pre-Algebra",
        "generators": [gen_arithmetic, gen_order_of_operations, gen_integers,
                       gen_fractions, gen_percentage],
    },
    {
        "id": "algebra_core",
        "name_tr": "Cebir Temel (üretilmiş)",
        "name_en": "Algebra Core (generated)",
        "course": "Algebra",
        "generators": [gen_linear_equation, gen_quadratic, gen_system2,
                       gen_exponent, gen_slope],
    },
    {
        "id": "geometry_core",
        "name_tr": "Geometri Temel (üretilmiş)",
        "name_en": "Geometry Core (generated)",
        "course": "Geometry",
        "generators": [gen_rect_area, gen_pythagoras, gen_circle],
    },
    {
        "id": "linear_algebra_core",
        "name_tr": "Lineer Cebir Temel (üretilmiş)",
        "name_en": "Linear Algebra Core (generated)",
        "course": "Linear Algebra",
        "generators": [gen_matrix_det2, gen_matrix_add, gen_dot_product],
    },
    {
        "id": "calculus_intro",
        "name_tr": "Kalkülüs Giriş (üretilmiş)",
        "name_en": "Calculus Intro (generated)",
        "course": "Calculus",
        "generators": [gen_derivative_poly],
    },
]


def builtin_pack_info(pack, lang="tr"):
    return {
        "id": pack["id"],
        "name": pack["name_tr"] if lang == "tr" else pack["name_en"],
        "course": pack["course"],
        "kind": "generator",
        "license": BUILTIN_LICENSE,
        "attribution": BUILTIN_ATTRIBUTION,
        "source_url": "",
        "count": "∞",
        "langs": "tr, en",
    }


def generate(pack_id, count=20, lang="tr", seed=None, difficulty=None):
    """Generate `count` unique questions from a built-in pack.

    Returns a list of dicts: question/answer/topic/difficulty/course/lang/
    source_pack/license. Unlimited + exact answers + no third-party licence.
    """
    pack = next((p for p in BUILTIN_PACKS if p["id"] == pack_id), None)
    if pack is None:
        return []
    rng = random.Random(seed)
    gens = list(pack["generators"])
    out, seen, guard = [], set(), 0
    target = max(1, int(count or 1))
    while len(out) < target and guard < target * 60:
        guard += 1
        q, a, topic, diff = rng.choice(gens)(rng, lang)
        if difficulty and diff != difficulty:
            continue
        if q in seen:
            continue
        seen.add(q)
        out.append({
            "question": q, "answer": a, "topic": topic, "difficulty": diff,
            "course": pack["course"], "lang": lang, "source_pack": pack["id"],
            "license": BUILTIN_LICENSE, "attribution": BUILTIN_ATTRIBUTION,
        })
    return out


# ===========================================================================
# External JSON packs (user-downloaded, openly licensed)
# ===========================================================================
def _external_pack_path(folder=None):
    return Path(folder) if folder else PACKS_DIR


def load_external_packs(folder=None):
    """Read openly-licensed packs from `question_packs/*.json`.

    Required keys: id, name, questions[]. Recommended: course, lang, license,
    attribution, source_url. A pack with no `license` is flagged 'UNKNOWN' so the
    user is warned before importing it.
    """
    base = _external_pack_path(folder)
    packs = []
    try:
        if not base.exists():
            return packs
        dosyalar = sorted(base.glob("*.json")) + sorted(base.glob("*" + MCPACK_UZANTI))
        for p in dosyalar:
            zip_yolu = ""
            try:
                if p.suffix.lower() == MCPACK_UZANTI:
                    with zipfile.ZipFile(p) as z:
                        ok, _sebep = mcpack_arsiv_guvenli_mi(z)
                        if not ok:
                            continue      # zip bomb / asiri paket: sessizce atla
                        bilgi = z.getinfo(MCPACK_JSON)
                        if int(getattr(bilgi, "file_size", 0) or 0) > MCPACK_MAX_TOTAL_BYTES:
                            continue
                        data = json.loads(z.read(MCPACK_JSON).decode("utf-8"))
                    zip_yolu = str(p)
                else:
                    data = json.loads(p.read_text(encoding="utf-8"))
            except Exception:
                continue        # bozuk/yarim paket listeyi cokertmez
            qs = data.get("questions")
            if not isinstance(qs, list) or not qs:
                continue
            packs.append({
                "_zip": zip_yolu,
                "kind_detail": "mcpack" if zip_yolu else "json",
                "images": int(data.get("images") or 0),
                "id": str(data.get("id") or p.stem),
                "name": str(data.get("name") or p.stem),
                "course": str(data.get("course") or ""),
                "kind": "external",
                "license": str(data.get("license") or "UNKNOWN — check before use"),
                "attribution": str(data.get("attribution") or ""),
                "source_url": str(data.get("source_url") or ""),
                "count": len(qs),
                "langs": str(data.get("lang") or "?"),
                "_path": str(p),
                "_questions": qs,
            })
    except Exception:
        pass
    return packs


def external_questions(pack, count=None, difficulty=None):
    out = []
    for q in pack.get("_questions", []):
        if not isinstance(q, dict):
            continue
        text = str(q.get("question") or q.get("question_text") or "").strip()
        if not text:
            continue
        diff = str(q.get("difficulty") or "Medium")
        if difficulty and diff != difficulty:
            continue
        entry = {
            "question": text,
            "answer": str(q.get("answer") or q.get("answer_text") or ""),
            "topic": str(q.get("topic") or ""),
            "difficulty": diff,
            "course": str(q.get("course") or pack.get("course") or ""),
            "lang": str(q.get("lang") or pack.get("langs") or ""),
            "source_pack": pack["id"],
            "license": pack.get("license", ""),
            "attribution": pack.get("attribution", ""),
        }
        # Sikli sorular (A-E) paketten geldiginde siklarini kaybetmesin:
        # export_pack bu alanlari yazar, eski paketlerde yoklar ve atlanir.
        ch = q.get("choices")
        if isinstance(ch, list) and ch:
            entry["choices"] = [str(c) for c in ch]
            cc = str(q.get("correct_choice") or "").strip().upper()
            if cc:
                entry["correct_choice"] = cc
        # .mcpack: gorsel HENUZ cikarilmaz — yalniz nerede oldugu tasinir.
        # Cikarma ice aktarma aninda olur (onizleme diske dosya birakmasin).
        gorsel = _guvenli_gorsel_adi(q.get("image"))
        if gorsel and pack.get("_zip"):
            entry["image_in_pack"] = f"{MCPACK_IMAGES}/{gorsel}"
            entry["_zip"] = pack["_zip"]
        out.append(entry)
        if count and len(out) >= int(count):
            break
    return out


def list_packs(lang="tr", folder=None):
    """Built-in generator packs + any external JSON packs, for the picker."""
    return [builtin_pack_info(p, lang) for p in BUILTIN_PACKS] + load_external_packs(folder)


def get_questions(pack_id, count=20, lang="tr", difficulty=None, seed=None, folder=None):
    """Uniform accessor used by the UI: works for built-in and external packs."""
    if any(p["id"] == pack_id for p in BUILTIN_PACKS):
        return generate(pack_id, count=count, lang=lang, seed=seed, difficulty=difficulty)
    for p in load_external_packs(folder):
        if p["id"] == pack_id:
            return external_questions(p, count=count, difficulty=difficulty)
    return []


IMAGE_ONLY_PREFIX = "[Görsel soru]"


def is_image_only(text):
    """Kirpilmis-gorsel placeholder metnini tanir (paketlere yazilamaz).

    Hem export_pack hem UI ayni kurali kullansin diye tek yerde."""
    t = str(text or "").strip()
    return (not t) or t.startswith(IMAGE_ONLY_PREFIX)


def export_pack(rows, path, name="", course="", lang="tr",
                license_text="", attribution="", source_url="",
                include_images=None):
    """Soru bankasi satirlarini (sqlite3.Row/dict) harici paket JSON'una yazar.

    Cikti, load_external_packs'in okudugu semanin aynisidir: dosya bir
    arkadasin question_packs/ klasorune kopyalandiginda Soru Paketleri
    sekmesinden dogrudan ice aktarilabilir. Lisans bos birakilirsa yukleyici
    paketi UNKNOWN olarak isaretler ve aktarmadan once uyari cikar — kisisel
    paylasim icin bu bilincli bir varsayilandir.

    BICIM (V48): dosya adi `.mcpack` ile bitiyorsa ZIP paketi yazilir
    (paket.json + images/) ve GORSELLI SORULAR DA TASINIR. `.json` ise eski
    duz bicim yazilir ve gorselden ibaret sorular atlanir — eski surumlerle
    ve arkadasin eski klonuyla uyum icin bu yol korunuyor.
    `include_images=True/False` ile bicim elle zorlanabilir.

    Hic yazilacak soru kalmazsa DOSYA OLUSTURULMAZ.
    Doner: (yazilan_sayisi, atlanan_sayisi).
    """
    p_on = Path(path)
    if include_images is None:
        include_images = p_on.suffix.lower() == MCPACK_UZANTI
    def _field(row, key, default=""):
        try:
            v = row[key]
        except (KeyError, IndexError, TypeError):
            return default
        return default if v is None else v

    questions = []
    skipped = 0
    gorseller = {}          # zip ici ad -> disk yolu
    for r in rows or []:
        text = str(_field(r, "question_text") or _field(r, "question") or "").strip()
        gorsel_yol = str(_field(r, "image_path") or "").strip()
        gorsel_var = bool(gorsel_yol) and Path(gorsel_yol).exists()
        if is_image_only(text) and not (include_images and gorsel_var):
            # Duz .json bicimi gorsel tasiyamaz; gorseli olmayan (ya da
            # dosyasi kayip) bir "gorsel soru" her iki bicimde de atlanir.
            skipped += 1
            continue
        entry = {
            "question": text,
            "answer": str(_field(r, "answer_text") or _field(r, "answer") or ""),
            "topic": str(_field(r, "topic") or ""),
            "difficulty": str(_field(r, "difficulty") or "Medium"),
        }
        # Satirin kendi ders/dil bilgisi tasinir; bos ise yukleyici paket
        # duzeyindeki degerlere duser (karisik bankalarda 'en' soru 'tr'
        # damgalanmasin, ders bilgisi silinmesin).
        row_course = str(_field(r, "course") or "").strip()
        if row_course:
            entry["course"] = row_course
        row_lang = str(_field(r, "lang") or "").strip()
        if row_lang:
            entry["lang"] = row_lang
        choices = _field(r, "choices", None)
        if isinstance(choices, str) and choices.strip():
            try:
                choices = json.loads(choices)
            except Exception:
                choices = None
        if isinstance(choices, list) and choices:
            entry["choices"] = [str(c) for c in choices]
            cc = str(_field(r, "correct_choice") or "").strip().upper()
            if cc:
                entry["correct_choice"] = cc
        if include_images and gorsel_var:
            # Zip icindeki ad benzersiz olmali: ayni dosya adi iki farkli
            # kaynaktan gelebilir, ustune yazmak sessiz veri kaybi olurdu.
            kaynak = Path(gorsel_yol)
            ad = kaynak.name
            sayac = 1
            while ad in gorseller and gorseller[ad] != str(kaynak):
                ad = f"{kaynak.stem}_{sayac}{kaynak.suffix}"
                sayac += 1
            gorseller[ad] = str(kaynak)
            entry["image"] = f"{MCPACK_IMAGES}/{ad}"
        questions.append(entry)

    if not questions:
        return 0, skipped

    from datetime import date
    stem = Path(path).stem
    data = {
        "id": stem,
        "name": str(name or stem),
        "course": str(course or ""),
        "lang": str(lang or "tr"),
        "license": str(license_text or ""),
        "attribution": str(attribution or ""),
        "source_url": str(source_url or ""),
        "exported_at": date.today().isoformat(),
        "exported_with": "Math Course AI",
        "questions": questions,
    }
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    if include_images:
        data["format"] = "mcpack/1"
        data["images"] = len(gorseller)
        with zipfile.ZipFile(p, "w", zipfile.ZIP_DEFLATED) as z:
            z.writestr(MCPACK_JSON, json.dumps(data, ensure_ascii=False, indent=2))
            for ad, kaynak in gorseller.items():
                try:
                    z.write(kaynak, f"{MCPACK_IMAGES}/{ad}")
                except Exception:
                    pass        # tek bir gorsel okunamazsa paket yine yazilir
    else:
        p.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    return len(questions), skipped


def import_into_store(store, pack_id, count=20, lang="tr", difficulty=None,
                      seed=None, folder=None):
    """Add pack questions to a StudentStore question bank. Skips duplicates by
    (question_text). Returns the number actually added."""
    rows = get_questions(pack_id, count=count, lang=lang, difficulty=difficulty,
                         seed=seed, folder=folder)
    if not rows:
        return 0
    existing = {(r["question_text"] or "").strip() for r in store.list_questions(limit=100000)}
    added = 0
    for r in rows:
        if r["question"].strip() in existing:
            continue
        qid = store.add_question(
            r["question"], r["answer"], course=r["course"], topic=r["topic"],
            difficulty=r["difficulty"], tags=r["source_pack"],
            source_pack=r["source_pack"], license_text=r["license"], lang=r["lang"],
            image_path=_gorseli_yerlestir(r),
            choices=r.get("choices"), correct_choice=r.get("correct_choice", ""))
        if qid:
            added += 1
            existing.add(r["question"].strip())
    return added


# --- .mcpack extraction limits -------------------------------------------
# A pack is untrusted user-supplied input. Zip-slip was already defended by
# _guvenli_gorsel_adi(); these caps close the remaining resource exhaustion
# (zip bomb) hole: an entry that declares 12 KB can still expand to gigabytes,
# and shutil.copyfileobj would happily write all of it.
MCPACK_MAX_IMAGE_BYTES = 8 * 1024 * 1024          # 8 MiB per extracted image
MCPACK_MAX_MEMBERS = 2000                          # members in one archive
MCPACK_MAX_TOTAL_BYTES = 256 * 1024 * 1024         # 256 MiB declared, whole pack
MCPACK_MAX_RATIO = 200                             # uncompressed / compressed


def mcpack_arsiv_guvenli_mi(zf, max_members=MCPACK_MAX_MEMBERS,
                            max_total=MCPACK_MAX_TOTAL_BYTES,
                            max_ratio=MCPACK_MAX_RATIO):
    """(ok, sebep) — archive-level sanity check BEFORE anything is extracted.

    Pure and testable: takes any object exposing `infolist()`.
    """
    bilgiler = list(zf.infolist())
    if len(bilgiler) > max_members:
        return False, ("uye sayisi cok yuksek / too many members: %d > %d"
                       % (len(bilgiler), max_members))
    toplam = sum(int(getattr(i, "file_size", 0) or 0) for i in bilgiler)
    if toplam > max_total:
        return False, ("acilmis boyut cok buyuk / declared size too large: %d > %d"
                       % (toplam, max_total))
    sikistirilmis = sum(int(getattr(i, "compress_size", 0) or 0) for i in bilgiler)
    if sikistirilmis > 0 and (toplam / sikistirilmis) > max_ratio:
        return False, ("sikistirma orani supheli / suspicious compression ratio: %.1fx > %dx"
                       % (toplam / sikistirilmis, max_ratio))
    return True, ""


def _sinirli_kopyala(kaynak, cikti, limit=MCPACK_MAX_IMAGE_BYTES, blok=64 * 1024):
    """copyfileobj with a hard byte ceiling. Raises ValueError past the limit."""
    yazilan = 0
    while True:
        parca = kaynak.read(blok)
        if not parca:
            return yazilan
        yazilan += len(parca)
        if yazilan > limit:
            raise ValueError("gorsel sinirin ustunde / image exceeds %d bytes" % limit)
        cikti.write(parca)


def _gorseli_yerlestir(entry):
    """.mcpack icindeki gorseli question_images klasorune cikarir → yol ya da "".

    Ayni adli bir dosya zaten varsa UZERINE YAZILMAZ; ad numaralanir. Hata
    yutulur: gorsel cikarilamasa da sorunun kendisi bankaya girsin.
    """
    rel = entry.get("image_in_pack")
    zip_yolu = entry.get("_zip")
    if not rel or not zip_yolu:
        return ""
    ad = _guvenli_gorsel_adi(rel)
    if not ad:
        return ""
    try:
        hedef_klasor = _gorsel_hedef_klasoru()
        hedef = hedef_klasor / ad
        sayac = 1
        while hedef.exists():
            hedef = hedef_klasor / f"{Path(ad).stem}_{sayac}{Path(ad).suffix}"
            sayac += 1
        with zipfile.ZipFile(zip_yolu) as z:
            ok, _sebep = mcpack_arsiv_guvenli_mi(z)
            if not ok:
                return ""
            bilgi = z.getinfo(rel)
            if int(getattr(bilgi, "file_size", 0) or 0) > MCPACK_MAX_IMAGE_BYTES:
                return ""
            try:
                with z.open(rel) as kaynak, open(hedef, "wb") as cikti:
                    _sinirli_kopyala(kaynak, cikti)
            except ValueError:
                # Beyan edilen boyut yalan soylemis olabilir: yarim dosyayi birakma.
                try:
                    hedef.unlink()
                except Exception:
                    pass
                return ""
        return str(hedef)
    except Exception:
        return ""
