# -*- coding: utf-8 -*-
"""Build the SYNTHETIC demo course library used for screenshots and the deck.

Why this exists
---------------
The presentation screenshots used to be photographs of the maintainer's own
machine. They therefore rendered

  * an absolute development path (``D:\\...\\Resources``), and
  * the folder names of a third party's commercial course catalogue,

neither of which belongs in a public repository. This script generates a
course tree that is obviously synthetic, contains no third-party brand and no
personal data, and produces its own sample PDF so nothing copyrighted is ever
opened during a capture.

Everything it writes is generated here and now. There is no real course
material, no learner data and no network access.

Usage:
    python tools/make_demo_resources.py [target_dir]
Default target: <repo>/demo_resources
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

#: Neutral, clearly-invented course names. No third-party trademark.
COURSES = [
    ("01 Demo Course - Foundations of Arithmetic", 3),
    ("02 Demo Course - Algebra Essentials", 4),
    ("03 Demo Course - Geometry Workshop", 3),
    ("04 Demo Course - Calculus I Sampler", 5),
    ("05 Demo Course - Linear Algebra Sampler", 3),
    ("06 Demo Course - Probability Sampler", 3),
]
SUBFOLDERS = ["01 Formula Sheet", "02 Notes", "03 Practice", "04 Review"]

PAGES = [
    ("Demo Course Notes - Foundations",
     ["This document is SYNTHETIC sample content generated by",
      "tools/make_demo_resources.py for screenshots and tests.",
      "",
      "It contains no third-party course material and no personal data.",
      "",
      "1. Order of operations",
      "   Evaluate brackets, then powers, then multiplication and division,",
      "   then addition and subtraction, left to right.",
      "",
      "   Example:  2 + 3 x 4 = 2 + 12 = 14"]),
    ("Fractions",
     ["2. Fractions",
      "",
      "   a/b + c/d = (a d + c b) / (b d),      b, d != 0",
      "",
      "   Example:  2/3 + 1/6 = (2*6 + 1*3) / 18 = 15/18 = 5/6",
      "",
      "   A fraction is in lowest terms when gcd(numerator, denominator) = 1."]),
    ("Quadratic equations",
     ["3. Quadratic equations",
      "",
      "   a x^2 + b x + c = 0,   a != 0",
      "",
      "   x = ( -b +/- sqrt(b^2 - 4 a c) ) / (2 a)",
      "",
      "   The discriminant D = b^2 - 4 a c decides the number of real roots:",
      "     D > 0  ->  two distinct real roots",
      "     D = 0  ->  one repeated real root",
      "     D < 0  ->  no real root (two complex roots)",
      "",
      "   Example:  x^2 - 5x + 6 = 0  ->  D = 1  ->  x = 2 or x = 3"]),
    ("Derivatives",
     ["4. Derivatives",
      "",
      "   d/dx (x^n)   = n x^(n-1)",
      "   d/dx (sin x) = cos x",
      "   d/dx (cos x) = -sin x",
      "   d/dx (e^x)   = e^x",
      "",
      "   Product rule:  (f g)' = f' g + f g'",
      "   Chain rule:    (f(g(x)))' = f'(g(x)) g'(x)"]),
    ("Integrals",
     ["5. Integrals",
      "",
      "   Integral of x^n dx = x^(n+1) / (n+1) + C,   n != -1",
      "   Integral of 1/x dx = ln|x| + C",
      "",
      "   Fundamental theorem of calculus:",
      "     Integral from a to b of f'(x) dx = f(b) - f(a)"]),
    ("Licence",
     ["Licence of this sample document",
      "",
      "Generated content, released into the public domain (CC0 1.0).",
      "No third-party material is reproduced here.",
      "",
      "Math Course AI - synthetic demo asset."]),
]


def write_sample_pdf(path: Path) -> None:
    """Render the sample PDF with PyMuPDF, falling back to a plain text file."""
    try:
        import fitz
    except Exception:
        path.with_suffix(".txt").write_text(
            "\n\n".join(t + "\n" + "\n".join(b) for t, b in PAGES), encoding="utf-8")
        print("   [!] PyMuPDF absent - wrote a .txt sample instead of a .pdf")
        return
    doc = fitz.open()
    for title, body in PAGES:
        page = doc.new_page(width=595, height=842)          # A4
        page.insert_text((60, 80), "Math Course AI - Demo Course Notes",
                         fontname="helv", fontsize=16)
        page.insert_text((60, 104), "SYNTHETIC SAMPLE - CC0 - no real course content",
                         fontname="helv", fontsize=9)
        page.insert_text((60, 150), title, fontname="hebo", fontsize=13)
        y = 185
        for line in body:
            page.insert_text((60, y), line, fontname="helv", fontsize=11)
            y += 19
    doc.set_metadata({"title": "Math Course AI - Demo Course Notes (synthetic)",
                      "author": "", "subject": "Synthetic sample content, CC0",
                      "keywords": "", "creator": "make_demo_resources.py",
                      "producer": "PyMuPDF"})
    path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(path))
    doc.close()
    print("   [OK] %s (%d pages)" % (path.name, len(PAGES)))


def build(target: Path) -> Path:
    target.mkdir(parents=True, exist_ok=True)
    (target / "_README.txt").write_text(
        "Synthetic demo course library for Math Course AI.\n"
        "Generated by tools/make_demo_resources.py. No third-party material,\n"
        "no personal data. Safe to delete and regenerate at any time.\n",
        encoding="utf-8")
    for course, n in COURSES:
        for sub in SUBFOLDERS[:n - 1] or SUBFOLDERS[:1]:
            (target / course / sub).mkdir(parents=True, exist_ok=True)
        notes = target / course / "02 Notes"
        notes.mkdir(parents=True, exist_ok=True)
        (notes / "_placeholder.txt").write_text(
            "Synthetic placeholder for %s.\n" % course, encoding="utf-8")
    write_sample_pdf(target / COURSES[0][0] / "02 Notes" / "Demo Course Notes (CC0).pdf")
    print("   [OK] demo course tree at", target)
    return target


if __name__ == "__main__":
    dest = Path(sys.argv[1]) if len(sys.argv) > 1 else (ROOT / "demo_resources")
    build(dest)
